-- cisco-pix
-- plugin_id: 1514
--
-- $Id: cisco-pix.sql,v 1.2 2009/10/05 13:29:43 juanmals Exp $
--

DELETE FROM plugin WHERE id = "1514";
DELETE FROM plugin_sid where plugin_id = "1514";

INSERT INTO plugin (id, type, name, description) VALUES (1514, 1, 'cisco-pix', 'Cisco Pix-ASA Firewall');

-- Alert Messages, Severity 1
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 101001, NULL, NULL, 'CiscoPIX: Failover cable OK', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 101002, NULL, NULL, 'CiscoPIX: Bad failover cable', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 101003, NULL, NULL, 'CiscoPIX: Failover cable not connected (this unit)', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 101004, NULL, NULL, 'CiscoPIX: Failover cable not connected (other unit)', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 101005, NULL, NULL, 'CiscoPIX: Error reading failover cable status', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 102001, NULL, NULL, 'CiscoPIX: Power failure/System reload other side', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 103001, NULL, NULL, 'CiscoPIX: No response from other firewall', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 103002, NULL, NULL, 'CiscoPIX: Other firewall network interface OK', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 103003, NULL, NULL, 'CiscoPIX: Other firewall network interface failed', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 103004, NULL, NULL, 'CiscoPIX: Other firewall reports this firewall failed', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 103005, NULL, NULL, 'CiscoPIX: Other firewall reporting failure', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 104001, NULL, NULL, 'CiscoPIX: Switching to ACTIVE', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 104002, NULL, NULL, 'CiscoPIX: Switching to STNDBY', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 104003, NULL, NULL, 'CiscoPIX: Switching to FAILED', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 104004, NULL, NULL, 'CiscoPIX: Switching to OK', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 105001, NULL, NULL, 'CiscoPIX: Disabling failover', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 105002, NULL, NULL, 'CiscoPIX: Enabling failover', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 105003, NULL, NULL, 'CiscoPIX: Monitoring waiting', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 105004, NULL, NULL, 'CiscoPIX: Monitoring normal', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 105005, NULL, NULL, 'CiscoPIX: Lost Failover communications with mate', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 105006, NULL, NULL, 'CiscoPIX: Link status UP', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 105007, NULL, NULL, 'CiscoPIX: Link status DOWN', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 105008, NULL, NULL, 'CiscoPIX: Testing interface', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 105009, NULL, NULL, 'CiscoPIX: Testing on interface', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 105011, NULL, NULL, 'CiscoPIX: Failover cable communication failure', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 105020, NULL, NULL, 'CiscoPIX: Incomplete/slow config replication', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 105031, NULL, NULL, 'CiscoPIX: Failover LAN interface is up', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 105032, NULL, NULL, 'CiscoPIX: LAN Failover interface is down', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 105034, NULL, NULL, 'CiscoPIX: Receive a LAN_FAILOVER_UP message from peer', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 105035, NULL, NULL, 'CiscoPIX: Receive a LAN failover interface down msg from peer', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 105036, NULL, NULL, 'CiscoPIX: PIX dropped a LAN Failover command message', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 105037, NULL, NULL, 'CiscoPIX: The primary and standby units are switching back and forth as the active unit', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 106021, NULL, NULL, 'CiscoPIX: Deny protocol reverse path check', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 106022, NULL, NULL, 'CiscoPIX: Deny protocol connection spoof', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 107001, NULL, NULL, 'CiscoPIX: RIP auth failed', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 107002, NULL, NULL, 'CiscoPIX: RIP pkt failed', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 709003, NULL, NULL, 'CiscoPIX: Beginning configuration replication: Receiving from mate', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 709004, NULL, NULL, 'CiscoPIX: End Configuration Replication (ACT)', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 709005, NULL, NULL, 'CiscoPIX: Beginning configuration replication: Receiving from mate', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 709006, NULL, NULL, 'CiscoPIX: End Configuration Replication (STB)', 3);

-- Critical Messages, Severity 2
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 106001, NULL, NULL, 'CiscoPIX: Inbound TCP connection denied', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 106002, NULL, NULL, 'CiscoPIX: protocol Connection denied', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 106006, NULL, NULL, 'CiscoPIX: Deny inbound UDP', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 106007, NULL, NULL, 'CiscoPIX: Deny inbound UDP due to DNS flag', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 106012, NULL, NULL, 'CiscoPIX: Deny', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 106013, NULL, NULL, 'CiscoPIX: Dropping echo request', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 106016, NULL, NULL, 'CiscoPIX: Deny IP spoof', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 106017, NULL, NULL, 'CiscoPIX: Deny IP due to Land Attack', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 106018, NULL, NULL, 'CiscoPIX: ICMP packet denied', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 106020, NULL, NULL, 'CiscoPIX: Deny IP teardrop fragment', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 108002, NULL, NULL, 'CiscoPIX: SMTP replaced chars', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 109011, NULL, NULL, 'CiscoPIX: Authen Session Start', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 112001, NULL, NULL, 'CiscoPIX: PIX Clear complete', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 201003, NULL, NULL, 'CiscoPIX: Embryonic limit exceeded neconns/elimit', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 214001, NULL, NULL, 'CiscoPIX: Terminating manager session. Reason: incoming encrypted data (number bytes) longer than upper_limit_number bytes', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 304007, NULL, NULL, 'CiscoPIX: URL Server IP_addr not responding, ENTERING ALLOW mode', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 304008, NULL, NULL, 'CiscoPIX: LEAVING ALLOW mode, URL Server is up', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 304009, NULL, NULL, 'CiscoPIX: Ran out of buffer blocks specified by url-block command', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 316001, NULL, NULL, 'CiscoPIX: Denied new tunnel to peer_IP. VPN peer limit (platform_vpn_peer_limit) exceeded', 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 709007, NULL, NULL, 'CiscoPIX: Configuration replication failed for command command_name', 3);

-- Error Messages, Severity 3
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 105010, NULL, NULL, 'CiscoPIX: Failover message block alloc failed', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 106010, NULL, NULL, 'CiscoPIX: Deny inbound protocol', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 106014, NULL, NULL, 'CiscoPIX: Deny inbound icmp', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 109010, NULL, NULL, 'CiscoPIX: Auth failed', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 109013, NULL, NULL, 'CiscoPIX: User must authenticate before using this service', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 109016, NULL, NULL, 'CiscoPIX: Can\'t find authorization ACL', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 109018, NULL, NULL, 'CiscoPIX: Downloaded ACL is empty', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 109019, NULL, NULL, 'CiscoPIX: Downloaded ACL has parsing error', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 109020, NULL, NULL, 'CiscoPIX: Downloaded ACL has config error', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 201002, NULL, NULL, 'CiscoPIX: Too many connections on gaddr!', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 201005, NULL, NULL, 'CiscoPIX: FTP data connection failed', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 201006, NULL, NULL, 'CiscoPIX: RCMD backconnection failed', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 201008, NULL, NULL, 'CiscoPIX: The PIX is disallowing new connections', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 201009, NULL, NULL, 'CiscoPIX: TCP connection limit exceeded', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 202001, NULL, NULL, 'CiscoPIX: Out of address translation slots!', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 202005, NULL, NULL, 'CiscoPIX: Non-embryonic in embryonic list', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 208005, NULL, NULL, 'CiscoPIX: pix clear', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 210001, NULL, NULL, 'CiscoPIX: LU SW_Module error', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 210002, NULL, NULL, 'CiscoPIX: LU allocate block failed', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 210003, NULL, NULL, 'CiscoPIX: Unknown LU Object ID', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 210005, NULL, NULL, 'CiscoPIX: LU allocate connection failed', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 210006, NULL, NULL, 'CiscoPIX: LU look NAT failed', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 210007, NULL, NULL, 'CiscoPIX: LU allocate xlate failed', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 210008, NULL, NULL, 'CiscoPIX: LU no xlate', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 210010, NULL, NULL, 'CiscoPIX: LU make UDP connection', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 210020, NULL, NULL, 'CiscoPIX: LU PAT port reserve failed', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 210021, NULL, NULL, 'CiscoPIX: LU create static xlate failed', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 211001, NULL, NULL, 'CiscoPIX: Memory allocation Error', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 211003, NULL, NULL, 'CiscoPIX: CPU utilization for time seconds', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 212001, NULL, NULL, 'CiscoPIX: Unable to open SNMP channel', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 212002, NULL, NULL, 'CiscoPIX: Unable to open SNMP trap channel', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 212003, NULL, NULL, 'CiscoPIX: Unable to receive an SNMP request', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 212004, NULL, NULL, 'CiscoPIX: Unable to send an SNMP response', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 212005, NULL, NULL, 'CiscoPIX: incoming SNMP request exceeds data buffer size, discarding this SNMP request', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 213001, NULL, NULL, 'CiscoPIX: PPTP control daemon socket io string', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 213002, NULL, NULL, 'CiscoPIX: PPTP tunnel hashtable insert failed', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 213003, NULL, NULL, 'CiscoPIX: PPP virtual interface number isn\'t opened', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 213004, NULL, NULL, 'CiscoPIX: PPP virtual interface number client ip allocation failed', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 302302, NULL, NULL, 'CiscoPIX: ACL = deny; no sa created', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 304003, NULL, NULL, 'CiscoPIX: Server timed out', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 304006, NULL, NULL, 'CiscoPIX: Server not respondig', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 305005, NULL, NULL, 'CiscoPIX: No traslation group found for protocol', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 305006, NULL, NULL, 'CiscoPIX: Regular traslation creation failed for protocol', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 305008, NULL, NULL, 'CiscoPIX: Free unallocated global IP address', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 313001, NULL, NULL, 'CiscoPIX: Denied ICMP', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 313003, NULL, NULL, 'CiscoPIX: Invalid destination for ICMP error', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 315004, NULL, NULL, 'CiscoPIX: Fail to establish SSH session because PIX RSA host key retrieval failed', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 403501, NULL, NULL, 'CiscoPIX: PPPoE - Bad host-unique in PADO - packet dropped', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 403502, NULL, NULL, 'CiscoPIX: PPPoE - Bad host-unique in PADS - dropping packet', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 403503, NULL, NULL, 'CiscoPIX: PPPoE:PPP link down', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 403504, NULL, NULL, 'CiscoPIX: PPPoE: No \'vpdn group\' for PPPoE is created', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 403505, NULL, NULL, 'CiscoPIX: PPPoE:PPP - Unable to set default route to address', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 403506, NULL, NULL, 'CiscoPIX: PPPoE:failed to assign PP address netmask', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 407002, NULL, NULL, 'CiscoPIX: Embryonic limit for through connections', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 610001, NULL, NULL, 'CiscoPIX: NTP daemon: Packet denied', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 610002, NULL, NULL, 'CiscoPIX: NTP daemon: Authentication failed', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 702302, NULL, NULL, 'CiscoPIX: replay rollover detected...', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 710003, NULL, NULL, 'CiscoPIX: access denied by ACL', 2);

-- Warning Messages, Severity 4
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 106023, NULL, NULL, 'CiscoPIX: Deny protocol', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 109017, NULL, NULL, 'CiscoPIX: User exceeded auth proxy connection limit', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 209003, NULL, NULL, 'CiscoPIX: Fragment database limit of counts exceeded', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 209004, NULL, NULL, 'CiscoPIX: Invalid IP fragment', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 209005, NULL, NULL, 'CiscoPIX: Discard IP fragment', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 308002, NULL, NULL, 'CiscoPIX: static gaddr1/laddr1 overlapped with gaddr2/laddr2', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 400000, NULL, NULL, 'CiscoPIX: sig_num sig_msg from IP_addr to IP_addr on interface', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 401001, NULL, NULL, 'CiscoPIX: Shuns cleared', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 401002, NULL, NULL, 'CiscoPIX: Shun added', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 401003, NULL, NULL, 'CiscoPIX: Shun add deleted', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 401004, NULL, NULL, 'CiscoPIX: Shunned packet', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 401005, NULL, NULL, 'CiscoPIX: Shun add failed', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 402101, NULL, NULL, 'CiscoPIX: decaps:rec\'d IPSEC packet has invalid spi for destaddr', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 402102, NULL, NULL, 'CiscoPIX: decapsulate: packet missing', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 402103, NULL, NULL, 'CiscoPIX: identity doesn\'t match negociated identity', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 402106, NULL, NULL, 'CiscoPIX: Rec\'d packet not an IPSEC packet', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 403101, NULL, NULL, 'CiscoPIX: PPTP session state not stablished, but received an XGRE packet', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 403102, NULL, NULL, 'CiscoPIX: PPP virtual interface rcvd pkt with invalid protocol', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 403103, NULL, NULL, 'CiscoPIX: PPP virtual interface max connections reached', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 403104, NULL, NULL, 'CiscoPIX: PPP virtual interface requires mschap for MPPE', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 403106, NULL, NULL, 'CiscoPIX: PPP virtual interface requires RADIUS for MPPE', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 403107, NULL, NULL, 'CiscoPIX: PPP virtual interface missing server group info', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 403108, NULL, NULL, 'CiscoPIX: PPP virtual interface missing client ip address', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 403109, NULL, NULL, 'CiscoPIX: Rec\'d packet not an PPTP packet', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 403110, NULL, NULL, 'CiscoPIX: PPP virtual interface', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 404101, NULL, NULL, 'CiscoPIX: ISAKMP:Failed to allocate address for client from pool', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 405101, NULL, NULL, 'CiscoPIX: Unable to Pre-allocate H225 Call Signalling Connection', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 405102, NULL, NULL, 'CiscoPIX: Unable to Pre-allocate H245 Connection', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 405103, NULL, NULL, 'CiscoPIX: H225 message contains bad protocol discriminator', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 406001, NULL, NULL, 'CiscoPIX: FTP low port', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 406002, NULL, NULL, 'CiscoPIX: FTP different address', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 407001, NULL, NULL, 'CiscoPIX: Deny traffic for local-host interface', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 500004, NULL, NULL, 'CiscoPIX: Invalid transport field for protocol', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 612002, NULL, NULL, 'CiscoPIX: Auto Update failed', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 612003, NULL, NULL, 'CiscoPIX: Auto Update failed to contact', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 710004, NULL, NULL, 'CiscoPIX: TCP connection limit exceeded', 2);

-- Notification Messages, Severity 5
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 109012, NULL, NULL, 'CiscoPIX: Authen Session End', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 111001, NULL, NULL, 'CiscoPIX: Begin configuration: IP_addr writing to device', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 111003, NULL, NULL, 'CiscoPIX: Erase configuration', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 111004, NULL, NULL, 'CiscoPIX: end configuration: FAILED|OK', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 111005, NULL, NULL, 'CiscoPIX: end configuration: OK', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 111007, NULL, NULL, 'CiscoPIX: Begin configuration', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 111008, NULL, NULL, 'CiscoPIX: User executed the command', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 199001, NULL, NULL, 'CiscoPIX: PIX reload command executed from telnet', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 304001, NULL, NULL, 'CiscoPIX: user Accessed JAVA URL', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 304002, NULL, NULL, 'CiscoPIX: Access denied URL', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 500001, NULL, NULL, 'CiscoPIX: ActiveX content', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 500002, NULL, NULL, 'CiscoPIX: Java content', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 500003, NULL, NULL, 'CiscoPIX: Bad TCP', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 501101, NULL, NULL, 'CiscoPIX: User transitioning priv level', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 502101, NULL, NULL, 'CiscoPIX: New user added to local dbase', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 502102, NULL, NULL, 'CiscoPIX: User deleted from local dbase', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 502103, NULL, NULL, 'CiscoPIX: User priv level changed', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 611103, NULL, NULL, 'CiscoPIX: User logged out', 2);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 612001, NULL, NULL, 'CiscoPIX: Auto Update suceeded', 2);

-- Informational Messages, Severity 6
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 106015, NULL, NULL, 'CiscoPIX: Deny TCP (no connection)', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 109001, NULL, NULL, 'CiscoPIX: Auth start', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 109002, NULL, NULL, 'CiscoPIX: Auth failed (server failed)', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 109003, NULL, NULL, 'CiscoPIX: Auth failed (all servers failed)', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 109005, NULL, NULL, 'CiscoPIX: Authentication succeeded', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 109006, NULL, NULL, 'CiscoPIX: Authentication failed', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 109007, NULL, NULL, 'CiscoPIX: Authorization permitted', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 109008, NULL, NULL, 'CiscoPIX: Authorization denied for user', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 109009, NULL, NULL, 'CiscoPIX: Authorization denied', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 109015, NULL, NULL, 'CiscoPIX: Authorization denied(acl) for user', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 110001, NULL, NULL, 'CiscoPIX: No route', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 199002, NULL, NULL, 'CiscoPIX: PIX startud completed. Beginning operation', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 199005, NULL, NULL, 'CiscoPIX: PIX Startup begin', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 210022, NULL, NULL, 'CiscoPIX: LU missed number updates', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 302003, NULL, NULL, 'CiscoPIX: Built H245 connection', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 302004, NULL, NULL, 'CiscoPIX: Pre-allocate H323 UDP backconnection', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 302009, NULL, NULL, 'CiscoPIX: Rebuilt TCP connection', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 302010, NULL, NULL, 'CiscoPIX: conns in use, conns most used', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 302013, NULL, NULL, 'CiscoPIX: Built TCP connection for interface', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 302014, NULL, NULL, 'CiscoPIX: Teardown TCP connection for interface', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 302015, NULL, NULL, 'CiscoPIX: Built UDP connection for interface', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 302016, NULL, NULL, 'CiscoPIX: Teardown UDP connection for interface', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 303002, NULL, NULL, 'CiscoPIX: src_addr Stored|Retrieved', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 304004, NULL, NULL, 'CiscoPIX: URL server request failed', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 305007, NULL, NULL, 'CiscoPIX: addrpool_fre(): Orphan IP', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 305009, NULL, NULL, 'CiscoPIX: Built translation from interface', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 305010, NULL, NULL, 'CiscoPIX: Teardown translation from interface', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 305011, NULL, NULL, 'CiscoPIX: Built TCP|UDP|ICMP translation from interface', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 305012, NULL, NULL, 'CiscoPIX: Built TCP|UDP|ICMP translation, duration ', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 308001, NULL, NULL, 'CiscoPIX: PIX console enable password incorrect for num tries', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 309002, NULL, NULL, 'CiscoPIX: Permitted manager connection', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 311001, NULL, NULL, 'CiscoPIX: LU loading standby start', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 311002, NULL, NULL, 'CiscoPIX: LU loading standby end', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 311003, NULL, NULL, 'CiscoPIX: LU recv thread up', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 311004, NULL, NULL, 'CiscoPIX: LU xmit thread up', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 312001, NULL, NULL, 'CiscoPIX: RIP hdr failed', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 314001, NULL, NULL, 'CiscoPIX: Pre-allocate RTSP UDP backconnection', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 315011, NULL, NULL, 'CiscoPIX: SSH session disconnected by SSH server', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 403500, NULL, NULL, 'CiscoPIX: PPPoE - Service name not received in PADO', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 602101, NULL, NULL, 'CiscoPIX: PMTU-D packet greater than effective mtu', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 602102, NULL, NULL, 'CiscoPIX: Adjusting IPSec tunnel mtu', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 602301, NULL, NULL, 'CiscoPIX: sa created...', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 602302, NULL, NULL, 'CiscoPIX: deleting sa', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 603101, NULL, NULL, 'CiscoPIX: PPTP received out of seq or duplicate pkt', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 603102, NULL, NULL, 'CiscoPIX: PPP virtual interface: authentication started', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 603103, NULL, NULL, 'CiscoPIX: PPP virtual interface: authentucation status', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 603104, NULL, NULL, 'CiscoPIX: PPTP Tunnel created', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 603105, NULL, NULL, 'CiscoPIX: PPTP Tunnel deleted', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 603106, NULL, NULL, 'CiscoPIX: L2TP Tunnel created', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 603107, NULL, NULL, 'CiscoPIX: L2TP Tunnel deleted', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 603108, NULL, NULL, 'CiscoPIX: Built PPTP Tunnel at interface', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 603109, NULL, NULL, 'CiscoPIX: Teardown PPPOE Tunnel at interface', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 604101, NULL, NULL, 'CiscoPIX: DHCP client interface: Allocated ip', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 604102, NULL, NULL, 'CiscoPIX: DHCP client interface: address released', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 604103, NULL, NULL, 'CiscoPIX: DHCP daemon interface: address granted', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 604104, NULL, NULL, 'CiscoPIX: DHCP daemon interface: address released', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 605004, NULL, NULL, 'CiscoPIX: Login denied for user', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 605005, NULL, NULL, 'CiscoPIX: Login permitted for user', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 606001, NULL, NULL, 'CiscoPIX: PDM session started', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 606002, NULL, NULL, 'CiscoPIX: PDM session ended', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 607001, NULL, NULL, 'CiscoPIX: Pre-allocate SIP secondary channel for outside-interface', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 608001, NULL, NULL, 'CiscoPIX: Pre-allocate Skinny secondary channel for outside-interface', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 609001, NULL, NULL, 'CiscoPIX: Built local-host', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 609002, NULL, NULL, 'CiscoPIX: Teardown local-host', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 610101, NULL, NULL, 'CiscoPIX: Authorization failed: Cmd', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 611101, NULL, NULL, 'CiscoPIX: User authentication succeeded', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 611102, NULL, NULL, 'CiscoPIX: User authentication failed', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 611301, NULL, NULL, 'CiscoPIX: VPNClient: NAT configured for Client Mode with no split tunneling', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 611302, NULL, NULL, 'CiscoPIX: VPNClient: NAT exemption configured for Network Extension Mode with no split tunneling', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 611303, NULL, NULL, 'CiscoPIX: VPNClient: NAT configured for CLient Mode with split tunneling', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 611304, NULL, NULL, 'CiscoPIX: VPNClient: NAT exemption configured for Network Extension with split tunneling', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 611305, NULL, NULL, 'CiscoPIX: VPNClient: DHCP Policy installed', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 611306, NULL, NULL, 'CiscoPIX: VPNClient: Perfect Forward Secrecy Policy installed', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 611307, NULL, NULL, 'CiscoPIX: VPNClient: Head end', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 611308, NULL, NULL, 'CiscoPIX: VPNClient: Split DNS Policy installed', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 611309, NULL, NULL, 'CiscoPIX: VPNClient: Disconnecting from head end and uninstalling previously downloaded policy: Head End', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 611310, NULL, NULL, 'CiscoPIX: VNPClient: XAUTH Suceeded', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 611311, NULL, NULL, 'CiscoPIX: VNPClient: XAUTH Failed', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 614001, NULL, NULL, 'CiscoPIX: Split DNS: request patched from server', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 614002, NULL, NULL, 'CiscoPIX: Split DNS: reply from server', 1);

-- Debugging Messages, Severity 7
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 106011, NULL, NULL, 'CiscoPIX: Deny inbound (No xlate) chars', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 109014, NULL, NULL, 'CiscoPIX: uauth_lookup_net fail for uauth_in()', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 111009, NULL, NULL, 'CiscoPIX: User executed cmd', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 304005, NULL, NULL, 'CiscoPIX: URL server request pending URL chars', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 701001, NULL, NULL, 'CiscoPIX: alloc_user() out of Tcp_user objects', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 702301, NULL, NULL, 'CiscoPIX: lifetime expiring...', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 702303, NULL, NULL, 'CiscoPIX: sa_request...', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 709001, NULL, NULL, 'CiscoPIX: FO replication failed', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 709002, NULL, NULL, 'CiscoPIX: FO unreplicable', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 710001, NULL, NULL, 'CiscoPIX: TCP access requested', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 710002, NULL, NULL, 'CiscoPIX: TCP|UDP access permitted', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 710005, NULL, NULL, 'CiscoPIX: TCP|UDP request discarded', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 710006, NULL, NULL, 'CiscoPIX: protocol request discarded', 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 302026, NULL, NULL, "CiscoPIX: Built ICMP connection for interface", 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 302020, NULL, NULL, "CiscoPIX: Built ICMP connection for faddr", 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 302021, NULL, NULL, "CiscoPIX: Teardown ICMP connection for faddr", 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 302027, NULL, NULL, "CiscoPIX: Teardown ICMP connection for interface", 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority) VALUES (1514, 110002, NULL, NULL, "CiscoPIX: Failed to locate egress interface for UDP from outside", 1);
