-- fortinet / fortigate
-- plugin_id: 1554
--
-- $Id: fortigate.sql,v 1.15 2010/03/15 11:43:43 dcanet Exp $
--
-- TODO: complete description for all sids using FortiOS Log Message Reference

DELETE FROM plugin WHERE id = "1554";
DELETE FROM plugin_sid where plugin_id = "1554";

INSERT INTO plugin (id, type, name, description) VALUES (1554, 1, 'fortigate', 'Fortinet / Fortigate');

INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 2, NULL, NULL, 'Fortigate: Allowed traffic');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 3, NULL, NULL, 'Fortigate: Drop Forbidden Traffic');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 10000, NULL, NULL, 'Fortigate: Traffic log Allowed (10000)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 10001, NULL, NULL, 'Fortigate: Traffic log Allowed (10001)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 12546, NULL, NULL, 'Fortigate: Url address blocked (it was found in URL filter list)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 12554, NULL, NULL, 'Fortigate: Url address blocked (it was found in URL filter list)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 13001, NULL, NULL, 'Fortigate: Traffic log Violation (13001)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 16001, NULL, NULL, 'Fortigate: Traffic log Policy other traffic: Traffic log for starting a session');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 16002, NULL, NULL, 'Fortigate: Traffic log Policy other traffic: Traffic log for allowed ICMP packet');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 16003, NULL, NULL, 'Fortigate: Traffic log Policy other traffic: Traffic for disallowed ICMP packet');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20001, NULL, NULL, 'Fortigate: Event log System Event (20001)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20002, NULL, NULL, 'Fortigate: Event log System Event (20002)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20031, NULL, NULL, 'Fortigate: Event log System Event (20031)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20032, NULL, NULL, 'Fortigate: Event log System Event (20032)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20033, NULL, NULL, 'Fortigate: Event log System Event (20033)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20034, NULL, NULL, 'Fortigate: Event log System Event (20034)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20035, NULL, NULL, 'Fortigate: Event log System Event (20035)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20036, NULL, NULL, 'Fortigate: Event log System Event (20036)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20037, NULL, NULL, 'Fortigate: Event log System Event (20037)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20038, NULL, NULL, 'Fortigate: Event log System Event (20038)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20039, NULL, NULL, 'Fortigate: Event log System Event (20039)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20040, NULL, NULL, 'Fortigate: Event log System Event (20040)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20041, NULL, NULL, 'Fortigate: Event log System Event (20041)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20043, NULL, NULL, 'Fortigate: Event log System Event (20043)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20044, NULL, NULL, 'Fortigate: Event log System Event (20044)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20045, NULL, NULL, 'Fortigate: Event log System Event (20045)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20046, NULL, NULL, 'Fortigate: Event log System Event (20046)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20047, NULL, NULL, 'Fortigate: Event log System Event (20047)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20048, NULL, NULL, 'Fortigate: Event log System Event (20048)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20049, NULL, NULL, 'Fortigate: Event log System Event (20049)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20050, NULL, NULL, 'Fortigate: Event log System Event (20050)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20051, NULL, NULL, 'Fortigate: Event log System Event: The IPv6 router advertisement daemon failed to set IPV6_MULTICAST_HOPS option');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20052, NULL, NULL, 'Fortigate: Event log System Event: The IPv6 router advertisement daemon failed to set IPV6_HOPLIMIT option');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20053, NULL, NULL, 'Fortigate: Event log System Event (20053)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20054, NULL, NULL, 'Fortigate: Event log System Event (20054)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20055, NULL, NULL, 'Fortigate: Event log System Event (20055)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20056, NULL, NULL, 'Fortigate: Event log System Event (20056)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20057, NULL, NULL, 'Fortigate: Event log System Event (20057)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20058, NULL, NULL, 'Fortigate: Event log System Event (20058)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20059, NULL, NULL, 'Fortigate: Event log System Event (20059)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20060, NULL, NULL, 'Fortigate: Event log System Event (20060)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20061, NULL, NULL, 'Fortigate: Event log System Event (20061)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20062, NULL, NULL, 'Fortigate: Event log System Event (20062)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20063, NULL, NULL, 'Fortigate: Event log System Event (20063)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20064, NULL, NULL, 'Fortigate: Event log System Event (20064)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20065, NULL, NULL, 'Fortigate: Event log System Event (20065)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20066, NULL, NULL, 'Fortigate: Event log System Event (20066)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20068, NULL, NULL, 'Fortigate: Event log System Event (20068)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20069, NULL, NULL, 'Fortigate: Event log System Event (20069)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20070, NULL, NULL, 'Fortigate: Event log System Event (20070)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20071, NULL, NULL, 'Fortigate: Event log System Event (20071)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20072, NULL, NULL, 'Fortigate: Event log System Event (20072)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20073, NULL, NULL, 'Fortigate: Event log System Event (20073)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20074, NULL, NULL, 'Fortigate: Event log System Event (20074)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20075, NULL, NULL, 'Fortigate: Event log System Event (20075)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20076, NULL, NULL, 'Fortigate: Event log System Event (20076)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20077, NULL, NULL, 'Fortigate: Event log System Event (20077)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20078, NULL, NULL, 'Fortigate: Event log System Event (20078)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20079, NULL, NULL, 'Fortigate: Event log System Event (20079)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20080, NULL, NULL, 'Fortigate: Event log System Event (20080)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20081, NULL, NULL, 'Fortigate: Event log System Event (20081)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20082, NULL, NULL, 'Fortigate: Event log System Event (20082)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20083, NULL, NULL, 'Fortigate: Event log System Event (20083)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20084, NULL, NULL, 'Fortigate: Event log System Event (20084)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20099, NULL, NULL, 'Fortigate: Event log System Event (20099)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20100, NULL, NULL, 'Fortigate: Event log System Event (20100)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20101, NULL, NULL, 'Fortigate: Event log System Event (20101)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20200, NULL, NULL, 'Fortigate: Event log System Event (20200)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20201, NULL, NULL, 'Fortigate: Event log System Event (20201)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20202, NULL, NULL, 'Fortigate: Event log System Event (20202)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 20203, NULL, NULL, 'Fortigate: Event log System Event (20203)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 22000, NULL, NULL, 'Fortigate: Event log System Event (22000)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 22001, NULL, NULL, 'Fortigate: Event log System Event (22001)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 22002, NULL, NULL, 'Fortigate: Event log System Event (22002)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 22004, NULL, NULL, 'Fortigate: Event log System Event (22004)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 22005, NULL, NULL, 'Fortigate: Event log System Event (22005)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 22006, NULL, NULL, 'Fortigate: Event log System Event (22006)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 22009, NULL, NULL, 'Fortigate: Event log System Event (22009)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 22010, NULL, NULL, 'Fortigate: Event log System Event Error (22010)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 22100, NULL, NULL, 'Fortigate: Event log System Event (22100)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 22101, NULL, NULL, 'Fortigate: Event log System Event (22101)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 22102, NULL, NULL, 'Fortigate: Event log System Event (22102)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 22103, NULL, NULL, 'Fortigate: Event log System Event (22103)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 22800, NULL, NULL, 'Fortigate: Event log System Event (22800)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 22801, NULL, NULL, 'Fortigate: Event log System Event (22801)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 22802, NULL, NULL, 'Fortigate: Event log System Event (22802)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 22803, NULL, NULL, 'Fortigate: Event log System Event (22803)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 22911, NULL, NULL, 'Fortigate: Event log System Event: The FortiGuard Analysis Service server is up');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 22912, NULL, NULL, 'Fortigate: Event log System Event: The FortiGuard Analysis Service server is down');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 22913, NULL, NULL, 'Fortigate: Event log System Event: The FortiGuard Analysis Service server has been disconnected');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 22914, NULL, NULL, 'Fortigate: Event log System Event: The FortiGuard Analysis Service server was changed to disabled on the FortiGuard Analysis and Management Service portal web site');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 23002, NULL, NULL, 'Fortigate: Event log IPSec Negotiation: IPSec generic negotiation report');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 23003, NULL, NULL, 'Fortigate: Event log IPSec Negotiation Error: Deleted IPSec phase1 SA');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 23004, NULL, NULL, 'Fortigate: Event log IPSec Negotiation: Deleted IPSec SA');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 23005, NULL, NULL, 'Fortigate: Event log IPSec Negotiation (23005)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 23006, NULL, NULL, 'Fortigate: Event log IPSec Negotiation (23006)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 23007, NULL, NULL, 'Fortigate: Event log IPSec Negotiation (23007)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 23008, NULL, NULL, 'Fortigate: Event log IPSec Negotiation (23008)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 23009, NULL, NULL, 'Fortigate: Event log IPSec Negotiation Variable (23009)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 23010, NULL, NULL, 'Fortigate: Event log IPSec Negotiation Variable (23010)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 23011, NULL, NULL, 'Fortigate: Event log IPSec Negotiation Variable (23011)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 23012, NULL, NULL, 'Fortigate: Event log IPSec Negotiation Variable (23012)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 26001, NULL, NULL, 'Fortigate: Event log DHCP service event Error (26001)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 26002, NULL, NULL, 'Fortigate: Event log DHCP service event Error (26002)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 29001, NULL, NULL, 'Fortigate: Event log - L2TP/PPTP/PPPoE Variable (29001)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 29002, NULL, NULL, 'Fortigate: Event log - L2TP/PPTP/PPPoE (29002)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 29003, NULL, NULL, 'Fortigate: Event log - L2TP/PPTP/PPPoE (29003)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 29004, NULL, NULL, 'Fortigate: Event log - L2TP/PPTP/PPPoE: The maximum number of PPTP connections has been reached');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 29009, NULL, NULL, 'Fortigate: Event log - L2TP/PPTP/PPPoE (29009)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 29011, NULL, NULL, 'Fortigate: Event log - L2TP/PPTP/PPPoE Error (29011)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 29012, NULL, NULL, 'Fortigate: Event log - L2TP/PPTP/PPPoE Error (29012)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 29013, NULL, NULL, 'Fortigate: Event log - L2TP/PPTP/PPPoE (29013)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 29014, NULL, NULL, 'Fortigate: Event log - L2TP/PPTP/PPPoE (29014)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 29015, NULL, NULL, 'Fortigate: Event log - L2TP/PPTP/PPPoE Error (29015)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 29016, NULL, NULL, 'Fortigate: Event log - L2TP/PPTP/PPPoE Error (29016)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 29022, NULL, NULL, 'Fortigate: Event log - L2TP/PPTP/PPPoE: No IP addresses are available');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 29024, NULL, NULL, 'Fortigate: Event log - L2TP/PPTP/PPPoE: Not enough memory');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 30004, NULL, NULL, 'Fortigate: Event log L2TP/PPTP/PPPOE Variable: PPPTPD start');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 30005, NULL, NULL, 'Fortigate: Event log - L2TP/PPTP/PPPoE Error: PPPTPD failed to start');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 30006, NULL, NULL, 'Fortigate: Event log - L2TP/PPTP/PPPoE: PPPTPD exited successfully');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 30007, NULL, NULL, 'Fortigate: Event log - L2TP/PPTP/PPPoE Error (30007)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 30008, NULL, NULL, 'Fortigate: Event log - L2TP/PPTP/PPPoE (30008)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 30009, NULL, NULL, 'Fortigate: Event log - L2TP/PPTP/PPPoE (30009)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 31004, NULL, NULL, 'Fortigate: Event log - L2TP/PPTP/PPPoE Variable (31004)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 31005, NULL, NULL, 'Fortigate: Event log - L2TP/PPTP/PPPoE (31005)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 31006, NULL, NULL, 'Fortigate: Event log - L2TP/PPTP/PPPoE/Warning (31006)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 31007, NULL, NULL, 'Fortigate: Event log - L2TP/PPTP/PPPoE (31007)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 31008, NULL, NULL, 'Fortigate: Event log - L2TP/PPTP/PPPoE (31008)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 31009, NULL, NULL, 'Fortigate: Event log - L2TP/PPTP/PPPoE (31009)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32001, NULL, NULL, 'Fortigate: Event Log - Administration Event: An administrator logged in successfully');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32002, NULL, NULL, 'Fortigate: Event Log - Administration Event: An administrator failed to log in');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32003, NULL, NULL, 'Fortigate: Event Log - Administration Event: An administrator logged out');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32004, NULL, NULL, 'Fortigate: Event Log - Administration Event (32004)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32005, NULL, NULL, 'Fortigate: Event Log - Administration Event (32005)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32006, NULL, NULL, 'Fortigate: Event Log - Administration Event: The specified administrator has logged in to the system successfully');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32007, NULL, NULL, 'Fortigate: Event Log - Administration Event (32007)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32008, NULL, NULL, 'Fortigate: Event Log - Administration Event (32008)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32009, NULL, NULL, 'Fortigate: Event Log - Administration Event (32009)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32010, NULL, NULL, 'Fortigate: Event Log - Administration Event (32010)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32011, NULL, NULL, 'Fortigate: Event Log - Administration Event: The log disk is full');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32012, NULL, NULL, 'Fortigate: Event Log - Administration Event (32012)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32013, NULL, NULL, 'Fortigate: Event Log - Administration Event: A user has cleared FortiGuard Analysis Service logs from the specified location');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32014, NULL, NULL, 'Fortigate: Event Log - Administration Event (32014)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32015, NULL, NULL, 'Fortigate: Event Log - Administration Event (32015)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32016, NULL, NULL, 'Fortigate: Event Log - Administration Event: The FortiGuard Analysis Service disk quota is full and the system will either overwrite or stop logging when the quota is used');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32017, NULL, NULL, 'Fortigate: Event Log - Administration Event: The FortiGuard daily quota is reached');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32020, NULL, NULL, 'Fortigate: Event Log - Administration Event: A corrupted MAC packet was detected');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32021, NULL, NULL, 'Fortigate: Event Log - Administration Event (32021)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32022, NULL, NULL, 'Fortigate: Event Log - Administration Event (32022)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32086, NULL, NULL, 'Fortigate: Event Log - Administration Event (32086)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32087, NULL, NULL, 'Fortigate: Event Log - Administration Event (32087)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32095, NULL, NULL, 'Fortigate: Event Log - Administration Event (32095)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32101, NULL, NULL, 'Fortigate: Event Log - Administration Event (32101)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32102, NULL, NULL, 'Fortigate: Event Log - Administration Event Variable (32102)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32103, NULL, NULL, 'Fortigate: Event Log - Administration Event (32103)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32104, NULL, NULL, 'Fortigate: Event Log - Administration Event (32104)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32105, NULL, NULL, 'Fortigate: Event Log - Administration Event (32105)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32120, NULL, NULL, 'Fortigate: Event Log - Administration Event: An administrator added an object');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32121, NULL, NULL, 'Fortigate: Event Log - Administration Event: The user disabled the virtual domain root from the web-based manager, CLI or console');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32122, NULL, NULL, 'Fortigate: Event Log - Administration Event: Administrator delete action');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32123, NULL, NULL, 'Fortigate: Event Log - Administration Event: The administrator added the specified static route entry');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32124, NULL, NULL, 'Fortigate: Event Log - Administration Event: The administrator made the specified changes to the static route entry');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32125, NULL, NULL, 'Fortigate: Event Log - Administration Event: The administrator deleted the specified static route entry');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32126, NULL, NULL, 'Fortigate: Event Log - Administration Event: The administrator added a new firewall policy');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32127, NULL, NULL, 'Fortigate: Event Log - Administration Event: The administrator made the specified changes to a firewall policy');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32128, NULL, NULL, 'Fortigate: Event Log - Administration Event: The administrator deleted a firewall policy');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32129, NULL, NULL, 'Fortigate: Event Log - Administration Event: The administrator added a new local administrator');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32130, NULL, NULL, 'Fortigate: Event Log - Administration Event: The administrator changed the specified settings for a local administrator');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32131, NULL, NULL, 'Fortigate: Event Log - Administration Event: The administrator deleted the specified local administrator from the system');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32132, NULL, NULL, 'Fortigate: Event Log - Administration Event: The administrator added a RADIUS or TACACS+ server to the server list');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32133, NULL, NULL, 'Fortigate: Event Log - Administration Event: An administrator changed a RADIUS or TACACS+ server setting');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32134, NULL, NULL, 'Fortigate: Event Log - Administration Event: The administrator deleted the RADIUS or TACACS+ server from the server list');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32135, NULL, NULL, 'Fortigate: Event Log - Administration Event: The administrator added a new LDAP or IM/P2P server to the list');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32136, NULL, NULL, 'Fortigate: Event Log - Administration Event: The administrator made the specified changes to an LDAP server entry');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32137, NULL, NULL, 'Fortigate: Event Log - Administration Event: The administrator deleted the LDAP server from the list');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32138, NULL, NULL, 'Fortigate: Event Log - Administration Event: The administrator rebooted or shut down the FortiGate unit');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32139, NULL, NULL, 'Fortigate: Event Log - Administration Event (32139)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32140, NULL, NULL, 'Fortigate: Event Log - Administration Event: The administrator has changed the global settings');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32141, NULL, NULL, 'Fortigate: Event Log - Administration Event: DHCPD (client) or DHCPCD (server) log information');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32142, NULL, NULL, 'Fortigate: Event Log - Administration Event: The system backed up a configuration file');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32143, NULL, NULL, 'Fortigate: Event Log - Administration Event: The administrator changed the policy routing entry');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32144, NULL, NULL, 'Fortigate: Event Log - Administration Event: An administrator added a policy routing entry');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32145, NULL, NULL, 'Fortigate: Event Log - Administration Event: An administrator deleted a policy routing entry');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32148, NULL, NULL, 'Fortigate: Event Log - Administration Event: Configuration changed');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32149, NULL, NULL, 'Fortigate: Event Log - Administration Event: A command failure occurred');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32150, NULL, NULL, 'Fortigate: Event Log - Administration Event: An administrator has added a new protection profile or has changed the password of another administrator');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32151, NULL, NULL, 'Fortigate: Event Log - Administration Event: An administrator changed the specified protection profile');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32152, NULL, NULL, 'Fortigate: Event Log - Administration Event: An administrator deleted the specified protection profile');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32156, NULL, NULL, 'Fortigate: Event Log - Administration Event: An administrator changed a webfilter banned word entry');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32157, NULL, NULL, 'Fortigate: Event Log - Administration Event (32157)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32160, NULL, NULL, 'Fortigate: Event Log - Administration Event (32160)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32163, NULL, NULL, 'Fortigate: Event Log - Administration Event (32163)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32164, NULL, NULL, 'Fortigate: Event Log - Administration Event (32164)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32165, NULL, NULL, 'Fortigate: Event Log - Administration Event (32165)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32170, NULL, NULL, 'Fortigate: Event Log - Administration Event (32170)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32171, NULL, NULL, 'Fortigate: Event Log - Administration Event (32171)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32172, NULL, NULL, 'Fortigate: Event Log - Administration Event (32172)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32180, NULL, NULL, 'Fortigate: Event Log - Administration Event Error (32180)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32200, NULL, NULL, 'Fortigate: Event Log - Administration Event (32200)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32545, NULL, NULL, 'Fortigate: Event Log - Administration Event (32545)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 32546, NULL, NULL, 'Fortigate: Event Log - Administration Event (32546)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 35001, NULL, NULL, 'Fortigate: Event Log - HA activity (35001)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 38001, NULL, NULL, 'Fortigate: Event Log - Firewall Authentication (38001)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 38002, NULL, NULL, 'Fortigate: Event Log - Firewall Authentication (38002)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 38003, NULL, NULL, 'Fortigate: Event Log - Firewall Authentication (38003)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 38004, NULL, NULL, 'Fortigate: Succesful FSAE log in');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 38010, NULL, NULL, 'Fortigate: Event Log - Authentication Event (38010)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 38011, NULL, NULL, 'Fortigate: Event Log - Authentication Event (38011)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 38012, NULL, NULL, 'Fortigate: Event Log - Authentication Event (38012)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 38020, NULL, NULL, 'Fortigate: Event Log - Authentication Event (38020)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 39424, NULL, NULL, 'SSL WEB Tunnel up');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 39425, NULL, NULL, 'SSL WEB Tunnel down (timeout)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 39947, NULL, NULL, 'SSL VPN session start');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 41000, NULL, NULL, 'Fortigate: Event - Pattern update (41000)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 41001, NULL, NULL, 'Fortigate: Event - Pattern update (41001)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 41002, NULL, NULL, 'Fortigate: Event - Pattern update (41002)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 45001, NULL, NULL, 'Fortigate: Event Log VIP SSL Error (45001)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 45003, NULL, NULL, 'Fortigate: Event Log VIP SSL Error (45003)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 45005, NULL, NULL, 'Fortigate: Event-Log VIP SSL Error (45005)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 45007, NULL, NULL, 'Fortigate: Event Log VIP SSL Error (45007)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 45009, NULL, NULL, 'Fortigate: Event Log VIP SSL Error (45009)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 45011, NULL, NULL, 'Fortigate: Event Log VIP SSL Error (45011)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 45012, NULL, NULL, 'Fortigate: Event Log VIP SSL (45012)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 45013, NULL, NULL, 'Fortigate: Event Log VIP SSL Error (45013)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 45015, NULL, NULL, 'Fortigate: Event Log VIP SSL Error (45015)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 45017, NULL, NULL, 'Fortigate: Event Log VIP SSL Error (45017)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 45019, NULL, NULL, 'Fortigate: Event Log VIP SSL Error (45019)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 45023, NULL, NULL, 'Fortigate: Event Log VIP SSL Error (45023)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 45027, NULL, NULL, 'Fortigate: Event Log VIP SSL Error (45027)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 45029, NULL, NULL, 'Fortigate: Event Log VIP SSL Error (45029)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 45031, NULL, NULL, 'Fortigate: Event Log VIP SSL Error (45031)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 46001, NULL, NULL, 'Fortigate: Event-LDB-monitor (46001)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 46002, NULL, NULL, 'Fortigate: Event-LDB-monitor (46002)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 46003, NULL, NULL, 'Fortigate: Event-LDB-monitor (46003)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 46004, NULL, NULL, 'Fortigate: Event-LDB-monitor (46004)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 46005, NULL, NULL, 'Fortigate: Event-LDB-monitor (46005)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 46100, NULL, NULL, 'Fortigate: Event-LDB-monitor (46100)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 46101, NULL, NULL, 'Fortigate: Event-LDB-monitor (46101)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 47001, NULL, NULL, 'Fortigate: Event-his-performance (47001)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 60000, NULL, NULL, 'Fortigate: Antivirus Log: An email contains a file that appears to be infected');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 63000, NULL, NULL, 'Fortigate: Antivirus Log: An email containing a file has been blocked by the FortiGate unit');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 66000, NULL, NULL, 'Fortigate: Antivirus Log: A file exceeds size limit');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 70000, NULL, NULL, 'Fortigate: Attack log Signature event (70000)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 73001, NULL, NULL, 'Fortigate: Attack log Anomaly event (73001)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 80000, NULL, NULL, 'Fortigate: Spam Filter Log SMTP: The IP address was found in the IP black list');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 80003, NULL, NULL, 'Fortigate: Spam Filter Log SMTP: The sender email address was found in the email blacklist');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 80006, NULL, NULL, 'Fortigate: Spam Filter Log SMTP: The email message from the specified source was blocked because it contains a word from the banned word list');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 80008, NULL, NULL, 'Fortigate: Spam Filter Log SMTP: The email message from the specified source was blocked because it contains either one or more FortiGuard AntiSpam blocking URLs');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 83003, NULL, NULL, 'Fortigate: Spam Filter POP3: The sender email address was found in the email blacklist');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 83005, NULL, NULL, 'Fortigate: Spam Filter POP3: The email address was returned because the FortiGate unit failed to obtain the DNS record for the domain');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 83006, NULL, NULL, 'Fortigate: Spam Filter POP3: The email message from the specified source was blocked because it contains a word from the banned word list');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 83007, NULL, NULL, 'Fortigate: Spam Filter POP3: The sender email address is from an IP address that is in FortiGuard-AntiSpam blacklist');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 83008, NULL, NULL, 'Fortigate: Spam Filter POP3:  he email message from the specified source was blocked because it contains either one or more FortiGuard AntiSpam blocking URLs');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 83011, NULL, NULL, 'Fortigate: Spam Filter POP3: The sender email address is from an IP address that is in FortiGuard-AntiSpam whitelist');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 86006, NULL, NULL, 'Fortigate: Spam Filter IMAP: The email message from the specified source was blocked because it contains a word from the banned word list');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 91000, NULL, NULL, 'Fortigate: Web Filter Category Block (91000)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 91005, NULL, NULL, 'Fortigate: Web Filter Category Block (91005)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 91010, NULL, NULL, 'Fortigate: Web Filter Category Block (91010)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 93002, NULL, NULL, 'Fortigate: Web Filter Category Block (93002)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 93003, NULL, NULL, 'Fortigate: Web Filter URL Filter (93003)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 93004, NULL, NULL, 'Fortigate: Web Filter URL Filter (93004)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 93006, NULL, NULL, 'Fortigate: Web Filter URL Filter (93006)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 93007, NULL, NULL, 'Fortigate: Web Filter URL Filter (93007)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 93013, NULL, NULL, 'Fortigate: Web Filter Category Block (93013)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 99000, NULL, NULL, 'Fortigate: Web Filter Category Block (99000)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 99001, NULL, NULL, 'Fortigate: Web Filter Category Block Error (99001)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 99501, NULL, NULL, 'Fortigate: Web Filter Category Block (99501)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 99503, NULL, NULL, 'Fortigate: Event Log - Chassis Variable (99503)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 99504, NULL, NULL, 'Fortigate: Event Log - Chassis Variable (99504)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 99505, NULL, NULL, 'Fortigate: Event Log - Chassis Variable (99505)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 99506, NULL, NULL, 'Fortigate: Event Log - Chassis Variable (99506)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 99507, NULL, NULL, 'Fortigate: Event Log - Chassis Variable (99507)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 99508, NULL, NULL, 'Fortigate: Event Log - Chassis Variable (99508)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 99509, NULL, NULL, 'Fortigate: Event Log - Chassis Variable (99509)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 99510, NULL, NULL, 'Fortigate: Web Filter FortiGuard (99510)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 99511, NULL, NULL, 'Fortigate: Web Filter FortiGuard Variable (99511)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 99601, NULL, NULL, 'Fortigate: Event Log SSL VPN user (99601)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 99602, NULL, NULL, 'Fortigate: SSL-VPN Log SSL VPN user (99602)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 99603, NULL, NULL, 'Fortigate: SSL-VPN Log SSL VPN user (99603)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 99604, NULL, NULL, 'Fortigate: SSL-VPN Log SSL VPN user (99604)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 99703, NULL, NULL, 'Fortigate: SSL-VPN Log SSL VPN administrator (99703)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 99705, NULL, NULL, 'Fortigate: SSL-VPN Log SSL VPN administrator (99705)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 99706, NULL, NULL, 'Fortigate: SSL-VPN Log SSL VPN administrator (99706)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 99707, NULL, NULL, 'Fortigate: SSL-VPN Log SSL VPN administrator (99707)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 99709, NULL, NULL, 'Fortigate: SSL-VPN Log SSL VPN administrator (99709)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 99805, NULL, NULL, 'Fortigate: SSL-VPN Log SSL VPN session (99805)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 99806, NULL, NULL, 'Fortigate: SSL-VPN Log SSL VPN session (99806)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 99807, NULL, NULL, 'Fortigate: SSL-VPN Log SSL VPN session (99807)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 99808, NULL, NULL, 'Fortigate: SSL-VPN Log SSL VPN session (99808)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 99809, NULL, NULL, 'Fortigate: SSL-VPN Log SSL VPN session (99809)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 99810, NULL, NULL, 'Fortigate: SSL-VPN Log SSL VPN session (99810)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 99811, NULL, NULL, 'Fortigate: SSL-VPN Log SSL VPN session (99811)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 99812, NULL, NULL, 'Fortigate: SSL-VPN Log SSL VPN session (99812)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 99820, NULL, NULL, 'Fortigate: SSL-VPN Log SSL VPN session (99820)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 99825, NULL, NULL, 'Fortigate: SSL-VPN Log SSL VPN session (99825)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 99826, NULL, NULL, 'Fortigate: SSL-VPN Log SSL VPN session (99826)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 99827, NULL, NULL, 'Fortigate: SSL-VPN Log SSL VPN session (99827)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 99840, NULL, NULL, 'Fortigate: SSL-VPN Log SSL VPN session Error (99840)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 99841, NULL, NULL, 'Fortigate: SSL-VPN Log SSL VPN session Error (99841)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 99842, NULL, NULL, 'Fortigate: SSL-VPN Log SSL VPN session Error (99842)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 99843, NULL, NULL, 'Fortigate: SSL-VPN Log SSL VPN session (99843)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 99844, NULL, NULL, 'Fortigate: SSL-VPN Log SSL VPN session (99844)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 103000, NULL, NULL, 'Fortigate: IM/P2P - An instant message was recorded or a p2p connection was established');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 106001, NULL, NULL, 'Fortigate: VoIP (106001)');
INSERT INTO `plugin_sid` (`plugin_id`, `sid`, `category_id`, `class_id`, `name`) VALUES(1554, 2000000000, NULL, NULL, 'Fortigate generic event');
