-- juniper/netscreen-firewall
-- plugin_id: 1522
--
-- $Id: netscreen-firewall.sql,v 1.9 2009/06/16 11:12:35 jaimeblasco Exp $
--
DELETE FROM plugin WHERE id = "1522";
DELETE FROM plugin_sid where plugin_id = "1522";


INSERT INTO plugin (id, type, name, description) VALUES (1522, 1, 'juniper-netscreen firewall', 'Juniper-Netscreen FW');

INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 1, 205, NULL, 'juniper/netscreen-fw: Permit');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 2, 206, NULL, 'juniper/netscreen-fw: Deny or Reject');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 3, 108, NULL, 'juniper/netscreen-fw: SYN flood');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 4, 103, NULL, 'juniper/netscreen-fw: Teardrop attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 5, 113, NULL, 'juniper/netscreen-fw: Ping of Death');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 6, 108, NULL, 'juniper/netscreen-fw: WinNuke attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 7, 103, NULL, 'juniper/netscreen-fw: IP spoofing');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 8, 103, NULL, 'juniper/netscreen-fw: Source Route IP option');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 9, 108, NULL, 'juniper/netscreen-fw: Land attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 10, 108, NULL, 'juniper/netscreen-fw: ICMP flood');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 11, 108, NULL, 'juniper/netscreen-fw: UDP flood');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 12, 132, NULL, 'juniper/netscreen-fw: Port scan');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 13, 103, NULL, 'juniper/netscreen-fw: Address sweep');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 14, 142, NULL, 'juniper/netscreen-fw: Malicious URL');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 15, 126, NULL, 'juniper/netscreen-fw: Src IP session limit');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 16, 103, NULL, 'juniper/netscreen-fw: SYN fragment');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 17, 103, NULL, 'juniper/netscreen-fw: No TCP flag');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 18, 103, NULL, 'juniper/netscreen-fw: Unknown protocol');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 19, 103, NULL, 'juniper/netscreen-fw: Bad IP option');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 20, 126, NULL, 'juniper/netscreen-fw: Dst IP session limit');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 21, 126, NULL, 'juniper/netscreen-fw: ZIP file blocked');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 22, 126, NULL, 'juniper/netscreen-fw: Java applet blocked');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 23, 126, NULL, 'juniper/netscreen-fw: EXE file blocked');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 24, 126, NULL, 'juniper/netscreen-fw: ActiveX control blocked');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 25, 103, NULL, 'juniper/netscreen-fw: ICMP fragment');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 26, 113, NULL, 'juniper/netscreen-fw: Large ICMP packet');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 27, 103, NULL, 'juniper/netscreen-fw: SYN and FIN bits');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 28, 103, NULL, 'juniper/netscreen-fw: FIN but no ACK bit');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 29, 108, NULL, 'juniper/netscreen-fw: SYN-ACK-ACK Proxy DoS');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 30, 103, NULL, 'juniper/netscreen-fw: Fragmented traffic');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 31, 107, NULL, 'juniper/netscreen-fw: DNS:EXPLOIT:CLASS-UNKNOWN attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 32, 107, NULL, 'juniper/netscreen-fw: DNS:EXPLOIT:EMPTY-UDP-MSG attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 33, 107, NULL, 'juniper/netscreen-fw: DNS:EXPLOIT:EXPLOIT-BIND9-RT attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 34, 107, NULL, 'juniper/netscreen-fw: DNS:EXPLOIT:POINTER-LOOP attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 35, 107, NULL, 'juniper/netscreen-fw: DNS:EXPLOIT:REQUEST-SHORT-MSG attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 36, 107, NULL, 'juniper/netscreen-fw: DNS:EXPLOIT:TYPE-AXFR attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 37, 107, NULL, 'juniper/netscreen-fw: DNS:EXPLOIT:TYPE-UNKNOWN attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 38, 107, NULL, 'juniper/netscreen-fw: DNS:HEADERERROR:INVALID-OPCODE attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 39, 107, NULL, 'juniper/netscreen-fw: DNS:OVERFLOW:BIN attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 40, 107, NULL, 'juniper/netscreen-fw: DNS:OVERFLOW:INVALID-LABEL-LEN attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 41, 107, NULL, 'juniper/netscreen-fw: DNS:OVERFLOW:INVALID-POINTER attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 42, 107, NULL, 'juniper/netscreen-fw: DNS:OVERFLOW:NAME-TOO-LONG attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 43, 107, NULL, 'juniper/netscreen-fw: DNS:OVERFLOW:OVERSIZED-UDP-MSG attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 44, 107, NULL, 'juniper/netscreen-fw: DNS:OVERFLOW:TOO-LONG-TCP-MSG attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 45, 107, NULL, 'juniper/netscreen-fw: DNS:REPERR:QCLASS-UNEXP attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 46, 107, NULL, 'juniper/netscreen-fw: DNS:REPERR:REP-MISMATCHING-AN attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 47, 107, NULL, 'juniper/netscreen-fw: DNS:REPERR:REP-MISMATCHING-QD attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 48, 107, NULL, 'juniper/netscreen-fw: DNS:REPERR:REP-QTYPE-UNEXPECTED attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 49, 107, NULL, 'juniper/netscreen-fw: DNS:REPERR:REP-S2C-QUERY attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 50, 107, NULL, 'juniper/netscreen-fw: DNS:REPERR:REQ-INVALID-HDR-RD attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 51, 107, NULL, 'juniper/netscreen-fw: DNS:REQERR:REQ-ANSWERS-IN-QUERY attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 52, 107, NULL, 'juniper/netscreen-fw: DNS:REQERR:REQ-C2S-RESPONSE attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 53, 107, NULL, 'juniper/netscreen-fw: DOS:NETDEV:IOS-HTTPD-DOS attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 54, 107, NULL, 'juniper/netscreen-fw: DOS:NETDEV:NETWORK-3COM-DOS attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 55, 112, NULL, 'juniper/netscreen-fw: FTP:COMMAND:PLATFTP-CD-DOS attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 56, 112, NULL, 'juniper/netscreen-fw: FTP:COMMAND:SITE-EXEC attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 57, 112, NULL, 'juniper/netscreen-fw: FTP:DIRECTORY:DOT-DOT attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 58, 112, NULL, 'juniper/netscreen-fw: FTP:DIRECTORY:DOT-PCT-20-DOT attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 59, 112, NULL, 'juniper/netscreen-fw: FTP:EXPLOIT:BOUNCE-ATTACK attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 60, 112, NULL, 'juniper/netscreen-fw: FTP:EXPLOIT:ILLEGAL-PORT attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 61, 112, NULL, 'juniper/netscreen-fw: FTP:EXPLOIT:SYNTAX-ERROR attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 62, 112, NULL, 'juniper/netscreen-fw: FTP:MS-FTP:ASTERISK attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 63, 112, NULL, 'juniper/netscreen-fw: FTP:MS-FTP:STAT-GLOB attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 64, 112, NULL, 'juniper/netscreen-fw: FTP:OVERFLOW:BSD-FTPD-MKD-OF attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 65, 112, NULL, 'juniper/netscreen-fw: FTP:OVERFLOW:FREEBSD-FTPD-GLOB attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 66, 112, NULL, 'juniper/netscreen-fw: FTP:OVERFLOW:LINE_TOO_LONG attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 67, 112, NULL, 'juniper/netscreen-fw: FTP:OVERFLOW:OPENBSD-X86 attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 68, 112, NULL, 'juniper/netscreen-fw: FTP:OVERFLOW:PASS_TOO_LONG attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 69, 112, NULL, 'juniper/netscreen-fw: FTP:OVERFLOW:PATH-LINUX-X86-1 attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 70, 112, NULL, 'juniper/netscreen-fw: FTP:OVERFLOW:PATH-LINUX-X86-2 attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 71, 112, NULL, 'juniper/netscreen-fw: FTP:OVERFLOW:PATH-LINUX-X86-3 attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 72, 112, NULL, 'juniper/netscreen-fw: FTP:OVERFLOW:PATH-TOO-LONG attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 73, 112, NULL, 'juniper/netscreen-fw: FTP:OVERFLOW:SITESTRING-2-LONG attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 74, 112, NULL, 'juniper/netscreen-fw: FTP:OVERFLOW:USERNAME-2-LONG attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 75, 112, NULL, 'juniper/netscreen-fw: FTP:OVERFLOW:WFTPD-MKD-OVERFLOW attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 76, 112, NULL, 'juniper/netscreen-fw: FTP:OVERFLOW:WUBSD-SE-RACE attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 77, 112, NULL, 'juniper/netscreen-fw: FTP:PABLO-FTP:FORMAT-STRING attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 78, 112, NULL, 'juniper/netscreen-fw: FTP:PASSWORD:4DGIFTS attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 79, 112, NULL, 'juniper/netscreen-fw: FTP:PASSWORD:H0TB0X attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 80, 112, NULL, 'juniper/netscreen-fw: FTP:PASSWORD:LRKR0X attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 81, 112, NULL, 'juniper/netscreen-fw: FTP:PASSWORD:SATORI attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 82, 112, NULL, 'juniper/netscreen-fw: FTP:PASSWORD:WH00T attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 83, 112, NULL, 'juniper/netscreen-fw: FTP:PROFTP:LOGXFR-OF1 attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 84, 112, NULL, 'juniper/netscreen-fw: FTP:PROFTP:MKD-OVERFLOW attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 85, 112, NULL, 'juniper/netscreen-fw: FTP:PROFTP:OVERFLOW1 attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 86, 112, NULL, 'juniper/netscreen-fw: FTP:PROFTP:PPC-FS1 attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 87, 112, NULL, 'juniper/netscreen-fw: FTP:PROFTP:PPC-FS2 attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 88, 112, NULL, 'juniper/netscreen-fw: FTP:PROFTP:SIZE-DOS2 attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 89, 112, NULL, 'juniper/netscreen-fw: FTP:PROFTP:USER-DOS attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 90, 112, NULL, 'juniper/netscreen-fw: FTP:REQERR:LOGIN-FAILED attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 91, 112, NULL, 'juniper/netscreen-fw: FTP:REQERR:REQ-INVALID-CMD-SEQ attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 92, 112, NULL, 'juniper/netscreen-fw: FTP:REQERR:REQ-MISSING-ARGS attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 93, 112, NULL, 'juniper/netscreen-fw: FTP:REQERR:REQ-NESTED-REQUEST attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 94, 112, NULL, 'juniper/netscreen-fw: FTP:REQERR:REQ-UNKNOWN-CMD attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 95, 112, NULL, 'juniper/netscreen-fw: FTP:RPLERR:REP-NESTED-REPLY attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 96, 112, NULL, 'juniper/netscreen-fw: FTP:WS-FTP:CPWD attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 97, 112, NULL, 'juniper/netscreen-fw: FTP:WU-FTP:DELE-OF attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 98, 112, NULL, 'juniper/netscreen-fw: FTP:WU-FTP:FTPD-BSD-X86 attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 99, 112, NULL, 'juniper/netscreen-fw: FTP:WU-FTP:GLOBARG attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 100, 112, NULL, 'juniper/netscreen-fw: FTP:WU-FTP:IREPLY-FS attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 101, 112, NULL, 'juniper/netscreen-fw: FTP:WU-FTP:LINUX-OF attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 102, 112, NULL, 'juniper/netscreen-fw: FTP:WU-FTP:REALPATH-OF attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 103, 112, NULL, 'juniper/netscreen-fw: FTP:WU-FTP:REALPATH-OF2 attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 104, 149, NULL, 'juniper/netscreen-fw: HTTP:APACHE:NOSEJOB attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 105, 149, NULL, 'juniper/netscreen-fw: HTTP:APACHE:PHP-INVALID-HDR attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 106, 149, NULL, 'juniper/netscreen-fw: HTTP:APACHE:SCALP attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 107, 140, NULL, 'juniper/netscreen-fw: HTTP:BIGBROTHER:DIR-TRAVERSAL attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 108, 141, NULL, 'juniper/netscreen-fw: HTTP:CGI:ALTAVISTA-TRAVERSAL attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 109, 141, NULL, 'juniper/netscreen-fw: HTTP:CGI:APPLE-QT-FILEDISC1 attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 110, 141, NULL, 'juniper/netscreen-fw: HTTP:CGI:BNB-SURVEY-REMOTE-EXEC attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 111, 141, NULL, 'juniper/netscreen-fw: HTTP:CGI:BUGZILLA-SEMICOLON attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 112, 141, NULL, 'juniper/netscreen-fw: HTTP:CGI:DCFORUM-AZ-EXEC attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 113, 141, NULL, 'juniper/netscreen-fw: HTTP:CGI:FORMMAIL-ENV-VAR attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 114, 141, NULL, 'juniper/netscreen-fw: HTTP:CGI:HASSAN-DIR-TRAVERSAL attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 115, 141, NULL, 'juniper/netscreen-fw: HTTP:CGI:HTDIG-INCLUSION attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 116, 141, NULL, 'juniper/netscreen-fw: HTTP:CGI:HYPERSEEK-DIR-TRAVERSL attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 117, 141, NULL, 'juniper/netscreen-fw: HTTP:CGI:INFOSRCH-REMOTE-EXEC attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 118, 141, NULL, 'juniper/netscreen-fw: HTTP:CGI:MOREOVER-CACHE-FEED attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 119, 141, NULL, 'juniper/netscreen-fw: HTTP:CGI:TECHNOTE-PRINT-DSCLSR attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 120, 141, NULL, 'juniper/netscreen-fw: HTTP:CGI:W3-MSQL-CGI attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 121, 141, NULL, 'juniper/netscreen-fw: HTTP:CGI:WEBPALS-EXEC attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 122, 141, NULL, 'juniper/netscreen-fw: HTTP:CGI:WEBSPEED-WSMADMIN attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 123, 141, NULL, 'juniper/netscreen-fw: HTTP:CGI:WEBSPIRS-FILE-DISCLSR attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 124, 141, NULL, 'juniper/netscreen-fw: HTTP:CGI:YABB-DIR-TRAVERSAL attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 125, 140, NULL, 'juniper/netscreen-fw: HTTP:CHKP-FW1-PROXY attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 126, 150, NULL, 'juniper/netscreen-fw: HTTP:CISCO:IOS-ADMIN-ACCESS attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 127, 150, NULL, 'juniper/netscreen-fw: HTTP:CISCO:VOIP:PORT-INFO-DOS attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 128, 150, NULL, 'juniper/netscreen-fw: HTTP:CISCO:VOIP:STREAM-ID-DOS attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 129, 143, NULL, 'juniper/netscreen-fw: HTTP:COLDFUSION:EXPRCALC-OPNFIL attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 130, 140, NULL, 'juniper/netscreen-fw: HTTP:DIR:TRAVERSE-DIRECTORY attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 131, 140, NULL, 'juniper/netscreen-fw: HTTP:EXPLOIT:AMBIG-CONTENT-LEN attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 132, 140, NULL, 'juniper/netscreen-fw: HTTP:EXPLOIT:BLAZIX-JSPVIEW attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 133, 144, NULL, 'juniper/netscreen-fw: HTTP:FRONTPAGE:ADMIN.PWD-REQ attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 134, 144, NULL, 'juniper/netscreen-fw: HTTP:FRONTPAGE:FOURDOTS attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 135, 144, NULL, 'juniper/netscreen-fw: HTTP:FRONTPAGE:SERVICE.PWD-REQ attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 136, 140, NULL, 'juniper/netscreen-fw: HTTP:HOSTCTRL:BROWSE-ASP attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 137, 145, NULL, 'juniper/netscreen-fw: HTTP:IIS:AD-SERVER-CONFIG attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 138, 145, NULL, 'juniper/netscreen-fw: HTTP:IIS:ASP-CODEBROWSER-EXAIR attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 139, 145, NULL, 'juniper/netscreen-fw: HTTP:IIS:BAT-& attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 140, 145, NULL, 'juniper/netscreen-fw: HTTP:IIS:COMMAND-EXEC attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 141, 145, NULL, 'juniper/netscreen-fw: HTTP:IIS:COMMAND-EXEC-2 attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 142, 145, NULL, 'juniper/netscreen-fw: HTTP:IIS:DATA-DISCLOSURE attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 143, 145, NULL, 'juniper/netscreen-fw: HTTP:IIS:DOUBLE-ENCODE attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 144, 145, NULL, 'juniper/netscreen-fw: HTTP:IIS:FACTO-CMS-SQL-INJ attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 145, 145, NULL, 'juniper/netscreen-fw: HTTP:IIS:HEADER-HOST-DOS attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 146, 145, NULL, 'juniper/netscreen-fw: HTTP:IIS:ISAPI-IDQ-OVERFLOW attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 147, 145, NULL, 'juniper/netscreen-fw: HTTP:IIS:ISAPI-PRINTER-OVERFLOW attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 148, 145, NULL, 'juniper/netscreen-fw: HTTP:IIS:MDAC-RDS attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 149, 145, NULL, 'juniper/netscreen-fw: HTTP:IIS:MDAC-RDS-2 attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 150, 145, NULL, 'juniper/netscreen-fw: HTTP:IIS:NEWDSN-FILE-CREATION attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 151, 145, NULL, 'juniper/netscreen-fw: HTTP:IIS:OUTLOOK-WEB-DOS attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 152, 145, NULL, 'juniper/netscreen-fw: HTTP:IIS:WEBDAV:MALFORMED-REQ1 attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 153, 145, NULL, 'juniper/netscreen-fw: HTTP:IIS:WEBDAV:MALFORMED-REQ2 attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 154, 146, NULL, 'juniper/netscreen-fw: HTTP:INFO-LEAK:VIGNETTE-LEAK attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 155, 146, NULL, 'juniper/netscreen-fw: HTTP:INFO-LEAK:WEB-INF-DOT attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 156, 141, NULL, 'juniper/netscreen-fw: HTTP:IRIX:CGI-BIN-WRAP attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 157, 146, NULL, 'juniper/netscreen-fw: HTTP:MISC:HP-PROCURVE-RESET attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 158, 146, NULL, 'juniper/netscreen-fw: HTTP:MISC:HTACCESS-ATTEMPT attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 159, 140, NULL, 'juniper/netscreen-fw: HTTP:NOVELL:NETWARE-CONVERT.BAS attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 160, 140, NULL, 'juniper/netscreen-fw: HTTP:OREILLY:WIN-C-SMPLE-OVFLOW attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 161, 140, NULL, 'juniper/netscreen-fw: HTTP:OVERFLOW:CHUNK-LEN-OFLOW attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 162, 140, NULL, 'juniper/netscreen-fw: HTTP:OVERFLOW:CHUNK-OVERFLOW attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 163, 140, NULL, 'juniper/netscreen-fw: HTTP:OVERFLOW:CONTENT-OVERFLOW attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 164, 140, NULL, 'juniper/netscreen-fw: HTTP:OVERFLOW:HEADER attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 165, 140, NULL, 'juniper/netscreen-fw: HTTP:OVERFLOW:INV-CHUNK-LEN attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 166, 140, NULL, 'juniper/netscreen-fw: HTTP:OVERFLOW:PI3WEB-SLASH-OF attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 167, 140, NULL, 'juniper/netscreen-fw: HTTP:OVERFLOW:URL-OVERFLOW attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 168, 147, NULL, 'juniper/netscreen-fw: HTTP:PHP:ACHIEVO-EXEC attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 169, 147, NULL, 'juniper/netscreen-fw: HTTP:PHP:DFORUM-PHP-INC attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 170, 147, NULL, 'juniper/netscreen-fw: HTTP:PHP:DOTPROJECT-USERCOOKIE attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 171, 147, NULL, 'juniper/netscreen-fw: HTTP:PHP:FI-DIR-TRAVERSAL attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 172, 147, NULL, 'juniper/netscreen-fw: HTTP:PHP:GALLERY-MAL-INCLUDE attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 173, 147, NULL, 'juniper/netscreen-fw: HTTP:PHP:MANTIS-ARB-EXEC1 attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 174, 147, NULL, 'juniper/netscreen-fw: HTTP:PHP:MANTIS-ARB-EXEC2 attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 175, 147, NULL, 'juniper/netscreen-fw: HTTP:PHP:MLOG-SCREEN attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 176, 147, NULL, 'juniper/netscreen-fw: HTTP:PHP:PHORUM:ADMIN-PW-CHG attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 177, 147, NULL, 'juniper/netscreen-fw: HTTP:PHP:PHORUM:READ-ACCESS attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 178, 147, NULL, 'juniper/netscreen-fw: HTTP:PHP:PHORUM:REMOTE-EXEC attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 179, 147, NULL, 'juniper/netscreen-fw: HTTP:PHP:PHPLIB-REMOTE-EXE attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 180, 147, NULL, 'juniper/netscreen-fw: HTTP:PHP:PHPNUKE:MODULES-DOS attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 181, 147, NULL, 'juniper/netscreen-fw: HTTP:PHP:PHPWEB-REMOTE-FILE attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 182, 147, NULL, 'juniper/netscreen-fw: HTTP:PHP:PMACHINE-INCLUDE attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 183, 147, NULL, 'juniper/netscreen-fw: HTTP:PHP:POSTNUKE-SQL-EXEC attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 184, 147, NULL, 'juniper/netscreen-fw: HTTP:PHP:REDHAT-PIRANHA-PASSWD attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 185, 147, NULL, 'juniper/netscreen-fw: HTTP:PHP:VBULL-CAL-EXEC attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 186, 147, NULL, 'juniper/netscreen-fw: HTTP:PHP:WOLTAB-SQL-INJ attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 187, 147, NULL, 'juniper/netscreen-fw: HTTP:PHP:YABBSE-PKG-EXEC attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 188, 147, NULL, 'juniper/netscreen-fw: HTTP:PHP:YABBSE-SSI-INCLUDE attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 189, 147, NULL, 'juniper/netscreen-fw: HTTP:PHP:ZENTRACK-CMD-EXEC attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 190, 146, NULL, 'juniper/netscreen-fw: HTTP:PKG:ALLAIRE-JRUN-DOS attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 191, 146, NULL, 'juniper/netscreen-fw: HTTP:PKG:DB4WEB-FILE-ACCESS-LIN attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 192, 146, NULL, 'juniper/netscreen-fw: HTTP:PKG:EWAVE-SERVLET-DOS attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 193, 146, NULL, 'juniper/netscreen-fw: HTTP:PKG:MOUNTAIN-ORDR-DSCLSR attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 194, 146, NULL, 'juniper/netscreen-fw: HTTP:PKG:WEBGAIS-REMOTE-EXEC attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 195, 142, NULL, 'juniper/netscreen-fw: HTTP:REQERR:REQ-INVALID-FORMAT attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 196, 142, NULL, 'juniper/netscreen-fw: HTTP:REQERR:REQ-LONG-UTF8CODE attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 197, 142, NULL, 'juniper/netscreen-fw: HTTP:REQERR:REQ-MALFORMED-URL attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 198, 151, NULL, 'juniper/netscreen-fw: HTTP:TOMCAT:JSP-AS-HTML attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 199, 151, NULL, 'juniper/netscreen-fw: HTTP:TOMCAT:SERVLET-DEVICE-DOS attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 200, 140, NULL, 'juniper/netscreen-fw: HTTP:WASD:CONF-ACCESS attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 201, 140, NULL, 'juniper/netscreen-fw: HTTP:WASD:DIR-TRAV attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 202, 152, NULL, 'juniper/netscreen-fw: HTTP:WEBLOGIC:URL-REVEAL-SRC attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 203, 152, NULL, 'juniper/netscreen-fw: HTTP:WEBLOGIC:WEBROOT attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 204, 140, NULL, 'juniper/netscreen-fw: HTTP:WEBPLUS:DIR-TRAVERSAL attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 205, 140, NULL, 'juniper/netscreen-fw: HTTP:WIN-CMD:WIN-RGUEST attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 206, 140, NULL, 'juniper/netscreen-fw: HTTP:WIN-CMD:WIN-WGUEST attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 207, 115, NULL, 'juniper/netscreen-fw: IMAP:OVERFLOW:COMMAND attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 208, 115, NULL, 'juniper/netscreen-fw: IMAP:OVERFLOW:FLAG attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 209, 115, NULL, 'juniper/netscreen-fw: IMAP:OVERFLOW:IMAP4-LSUB-OF attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 210, 115, NULL, 'juniper/netscreen-fw: IMAP:OVERFLOW:LINE attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 211, 115, NULL, 'juniper/netscreen-fw: IMAP:OVERFLOW:MAILBOX attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 212, 115, NULL, 'juniper/netscreen-fw: IMAP:OVERFLOW:PASS attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 213, 115, NULL, 'juniper/netscreen-fw: IMAP:OVERFLOW:REFERENCE attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 214, 115, NULL, 'juniper/netscreen-fw: IMAP:OVERFLOW:TAG attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 215, 115, NULL, 'juniper/netscreen-fw: IMAP:OVERFLOW:USER attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 216, 115, NULL, 'juniper/netscreen-fw: IMAP:REQERR:LOGIN-FAILED attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 217, 115, NULL, 'juniper/netscreen-fw: IMAP:REQERR:REQ-INVALID-STATE attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 218, 115, NULL, 'juniper/netscreen-fw: IMAP:REQERR:REQ-INVALID-TAG attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 219, 115, NULL, 'juniper/netscreen-fw: IMAP:REQERR:REQ-UNEXPECTED-ARG attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 220, 128, NULL, 'juniper/netscreen-fw: POP3:DOS:MDAEMON-POP-DOS attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 221, 128, NULL, 'juniper/netscreen-fw: POP3:OVERFLOW:APOP attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 222, 128, NULL, 'juniper/netscreen-fw: POP3:OVERFLOW:COMMAND attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 223, 128, NULL, 'juniper/netscreen-fw: POP3:OVERFLOW:LINE attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 224, 128, NULL, 'juniper/netscreen-fw: POP3:OVERFLOW:PASS attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 225, 128, NULL, 'juniper/netscreen-fw: POP3:OVERFLOW:QPOP-OF1 attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 226, 128, NULL, 'juniper/netscreen-fw: POP3:OVERFLOW:QPOP-OF2 attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 227, 128, NULL, 'juniper/netscreen-fw: POP3:OVERFLOW:QPOP-OF3 attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 228, 128, NULL, 'juniper/netscreen-fw: POP3:OVERFLOW:QPOP-OF4 attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 229, 128, NULL, 'juniper/netscreen-fw: POP3:OVERFLOW:USER attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 230, 128, NULL, 'juniper/netscreen-fw: POP3:REQERR:LOGIN-FAILED attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 231, 128, NULL, 'juniper/netscreen-fw: POP3:REQERR:REQ-INVALID-STATE attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 232, 128, NULL, 'juniper/netscreen-fw: POP3:REQERR:REQ-MESSAGE-NUMBER attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 233, 128, NULL, 'juniper/netscreen-fw: POP3:REQERR:REQ-NESTED-REQUEST attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 234, 128, NULL, 'juniper/netscreen-fw: POP3:REQERR:REQ-SYNTAX-ERROR attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 235, 128, NULL, 'juniper/netscreen-fw: POP3:REQERR:REQ-UNKNOWN-CMD attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 236, 133, NULL, 'juniper/netscreen-fw: SHELLCODE:AIX:NOOP-PKT attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 237, 133, NULL, 'juniper/netscreen-fw: SHELLCODE:BSDX86:GEN-1-PKT attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 238, 133, NULL, 'juniper/netscreen-fw: SHELLCODE:BSDX86:GEN-2-PKT attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 239, 133, NULL, 'juniper/netscreen-fw: SHELLCODE:DIGITAL:NOOP-PKT attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 240, 133, NULL, 'juniper/netscreen-fw: SHELLCODE:HP-UX:HP-NOOP-1-PKT attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 241, 133, NULL, 'juniper/netscreen-fw: SHELLCODE:HP-UX:HP-NOOP-2-PKT attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 242, 134, NULL, 'juniper/netscreen-fw: SMTP:COMMAND:DEBUG attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 243, 134, NULL, 'juniper/netscreen-fw: SMTP:COMMAND:ETRN attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 244, 134, NULL, 'juniper/netscreen-fw: SMTP:COMMAND:EXPN attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 245, 134, NULL, 'juniper/netscreen-fw: SMTP:COMMAND:SMTP-VRFY-CMD attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 246, 134, NULL, 'juniper/netscreen-fw: SMTP:COMMAND:TURN attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 247, 134, NULL, 'juniper/netscreen-fw: SMTP:COMMAND:VRFY attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 248, 134, NULL, 'juniper/netscreen-fw: SMTP:COMMAND:WIZ attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 249, 134, NULL, 'juniper/netscreen-fw: SMTP:EMAIL:HEADER-FROM-PIPE attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 250, 134, NULL, 'juniper/netscreen-fw: SMTP:EMAIL:HEADER-TO-PIPE attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 251, 134, NULL, 'juniper/netscreen-fw: SMTP:EMAIL:MAIL-FROM-PIPE attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 252, 134, NULL, 'juniper/netscreen-fw: SMTP:EMAIL:RCPT-TO-DECODE attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 253, 134, NULL, 'juniper/netscreen-fw: SMTP:EMAIL:RCPT-TO-PIPE attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 254, 134, NULL, 'juniper/netscreen-fw: SMTP:EMAIL:REPLY-TO-PIPE attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 255, 134, NULL, 'juniper/netscreen-fw: SMTP:EXCHANGE:DOS attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 256, 134, NULL, 'juniper/netscreen-fw: SMTP:MAJORDOMO:COMMAND-EXEC attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 257, 134, NULL, 'juniper/netscreen-fw: SMTP:MSSQL-WORM-EMAIL attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 258, 134, NULL, 'juniper/netscreen-fw: SMTP:OVERFLOW:COMMAND-LINE attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 259, 134, NULL, 'juniper/netscreen-fw: SMTP:OVERFLOW:EMAIL-ADDRESS attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 260, 134, NULL, 'juniper/netscreen-fw: SMTP:OVERFLOW:EMAIL-DOMAIN attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 261, 134, NULL, 'juniper/netscreen-fw: SMTP:OVERFLOW:EMAIL-USERNAME attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 262, 134, NULL, 'juniper/netscreen-fw: SMTP:OVERFLOW:OUTLOOK-CERT-OF attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 263, 134, NULL, 'juniper/netscreen-fw: SMTP:OVERFLOW:REPLY-LINE attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 264, 134, NULL, 'juniper/netscreen-fw: SMTP:OVERFLOW:SENDMAIL-CMT-OF1 attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 265, 134, NULL, 'juniper/netscreen-fw: SMTP:OVERFLOW:SENDMAIL-CMT-OF2 attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 266, 134, NULL, 'juniper/netscreen-fw: SMTP:OVERFLOW:TOO-MANY-RCPT attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 267, 134, NULL, 'juniper/netscreen-fw: SMTP:REPERR:REP-INVALID-REPLY attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 268, 134, NULL, 'juniper/netscreen-fw: SMTP:REPERR:REP-NESTED-REPLY attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 269, 134, NULL, 'juniper/netscreen-fw: SMTP:REQERR:REQ-INVALID-CMD-SEQ attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 270, 134, NULL, 'juniper/netscreen-fw: SMTP:REQERR:REQ-NESTED-REQUEST attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 271, 134, NULL, 'juniper/netscreen-fw: SMTP:REQERR:REQ-SYNTAX-ERROR attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 272, 134, NULL, 'juniper/netscreen-fw: SMTP:REQERR:REQ-UNKNOWN-CMD attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 273, 134, NULL, 'juniper/netscreen-fw: SMTP:RESPONSE:PIPE-FAILED attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 274, 134, NULL, 'juniper/netscreen-fw: SMTP:SENDMAIL:ADDR-PRESCAN-ATK attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 275, 134, NULL, 'juniper/netscreen-fw: SMTP:SENDMAIL:SENDMAIL-FF-OF attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 276, 139, NULL, 'juniper/netscreen-fw: TROJAN:QAZ:TCP25-CALLING-HOME attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 277, 139, NULL, 'juniper/netscreen-fw: WORM:CODERED-2:CMD-BACKDOOR attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 278, 139, NULL, 'juniper/netscreen-fw: WORM:CODERED-2:INFECT-ATTEMPT attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 279, 139, NULL, 'juniper/netscreen-fw: WORM:CODERED-2:ROOT-BACKDOOR attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 280, 139, NULL, 'juniper/netscreen-fw: WORM:NIMDA:BIN-255-CMD attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 281, 139, NULL, 'juniper/netscreen-fw: WORM:NIMDA:MSADC-ROOT attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 282, 139, NULL, 'juniper/netscreen-fw: WORM:NIMDA:SCRIPTS-C11C-CMD attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 283, 139, NULL, 'juniper/netscreen-fw: WORM:NIMDA:SCRIPTS-CMD attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 284, 139, NULL, 'juniper/netscreen-fw: WORM:NIMDA:SCRIPTS-ROOT attack');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 285, NULL, NULL, 'juniper/netscreen-fw: unknown');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 286, NULL, NULL, 'juniper/netscreen-fw: Remote admin user logged on');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 287, NULL, NULL, 'juniper/netscreen-fw: Remote admin user logged out');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 288, NULL, NULL, 'juniper/netscreen-fw: Remote admin logging attempt');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 289, NULL, NULL, 'juniper/netscreen-fw: Multiple login failures');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 290, NULL, NULL, 'juniper/netscreen-fw: Detected an IP conflict');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1522, 291, NULL, NULL, 'juniper/netscreen-fw: Tunnel Connection');


