-- snort preprocessors
-- type: detector
-- plugin_id: 1100-1139

-- DELETE FROM plugin WHERE id = "1001";
-- DELETE FROM plugin WHERE id = "1002";
-- DELETE FROM plugin WHERE id = "1003";
DELETE FROM plugin WHERE id = "1100";
DELETE FROM plugin WHERE id = "1101";
DELETE FROM plugin WHERE id = "1102";
DELETE FROM plugin WHERE id = "1103";
DELETE FROM plugin WHERE id = "1104";
DELETE FROM plugin WHERE id = "1105";
DELETE FROM plugin WHERE id = "1106";
DELETE FROM plugin WHERE id = "1107";
DELETE FROM plugin WHERE id = "1108";
DELETE FROM plugin WHERE id = "1109";
DELETE FROM plugin WHERE id = "1110";
DELETE FROM plugin WHERE id = "1111";
DELETE FROM plugin WHERE id = "1112";
DELETE FROM plugin WHERE id = "1113";
DELETE FROM plugin WHERE id = "1114";
DELETE FROM plugin WHERE id = "1115";
DELETE FROM plugin WHERE id = "1116";
DELETE FROM plugin WHERE id = "1117";
DELETE FROM plugin WHERE id = "1118";
DELETE FROM plugin WHERE id = "1119";
DELETE FROM plugin WHERE id = "1120";
DELETE FROM plugin WHERE id = "1121";
DELETE FROM plugin WHERE id = "1122";
DELETE FROM plugin WHERE id = "1123";
DELETE FROM plugin WHERE id = "1124";
DELETE FROM plugin WHERE id = "1125";
DELETE FROM plugin WHERE id = "1126";
DELETE FROM plugin WHERE id = "1128";
DELETE FROM plugin WHERE id = "1129";
DELETE FROM plugin WHERE id = "1130";
DELETE FROM plugin WHERE id = "1131";
DELETE FROM plugin WHERE id = "1133";
DELETE FROM plugin WHERE id = "1134";
DELETE FROM plugin WHERE id = "1135";
DELETE FROM plugin WHERE id = "1137";
DELETE FROM plugin WHERE id = "1138";
DELETE FROM plugin WHERE id = "1139";

-- DELETE FROM plugin_sid where plugin_id = "1001";
-- DELETE FROM plugin_sid where plugin_id = "1002";
-- DELETE FROM plugin_sid where plugin_id = "1003";
DELETE FROM plugin_sid where plugin_id = "1100";
DELETE FROM plugin_sid where plugin_id = "1101";
DELETE FROM plugin_sid where plugin_id = "1102";
DELETE FROM plugin_sid where plugin_id = "1103";
DELETE FROM plugin_sid where plugin_id = "1104";
DELETE FROM plugin_sid where plugin_id = "1105";
DELETE FROM plugin_sid where plugin_id = "1106";
DELETE FROM plugin_sid where plugin_id = "1107";
DELETE FROM plugin_sid where plugin_id = "1108";
DELETE FROM plugin_sid where plugin_id = "1109";
DELETE FROM plugin_sid where plugin_id = "1110";
DELETE FROM plugin_sid where plugin_id = "1111";
DELETE FROM plugin_sid where plugin_id = "1112";
DELETE FROM plugin_sid where plugin_id = "1113";
DELETE FROM plugin_sid where plugin_id = "1114";
DELETE FROM plugin_sid where plugin_id = "1116";
DELETE FROM plugin_sid where plugin_id = "1116";
DELETE FROM plugin_sid where plugin_id = "1117";
DELETE FROM plugin_sid where plugin_id = "1118";
DELETE FROM plugin_sid where plugin_id = "1119";
DELETE FROM plugin_sid where plugin_id = "1120";
DELETE FROM plugin_sid where plugin_id = "1121";
DELETE FROM plugin_sid where plugin_id = "1122";
DELETE FROM plugin_sid where plugin_id = "1123";
DELETE FROM plugin_sid where plugin_id = "1124";
DELETE FROM plugin_sid where plugin_id = "1125";
DELETE FROM plugin_sid where plugin_id = "1126";
DELETE FROM plugin_sid where plugin_id = "1128";
DELETE FROM plugin_sid where plugin_id = "1129";
DELETE FROM plugin_sid where plugin_id = "1130";
DELETE FROM plugin_sid where plugin_id = "1131";
DELETE FROM plugin_sid where plugin_id = "1133";
DELETE FROM plugin_sid where plugin_id = "1134";
DELETE FROM plugin_sid where plugin_id = "1135";
DELETE FROM plugin_sid where plugin_id = "1137";
DELETE FROM plugin_sid where plugin_id = "1138";
DELETE FROM plugin_sid where plugin_id = "1139";

-- INSERT INTO plugin (id, type, name, description) VALUES (1001, 1, 'snort', 'Snort General Alert');
-- INSERT INTO plugin (id, type, name, description) VALUES (1002, 1, 'tag', 'Snort Tagging');
-- INSERT INTO plugin (id, type, name, description) VALUES (1003, 1, 'snort', 'Snort Dynamic Alert');
INSERT INTO plugin (id, type, name, description) VALUES (1100, 1, 'spp_portscan', 'Portscan1');
INSERT INTO plugin (id, type, name, description) VALUES (1101, 1, 'spp_minfrag', 'Minfrag');
INSERT INTO plugin (id, type, name, description) VALUES (1102, 1, 'http_decode', 'HTTP decode 1/2');
INSERT INTO plugin (id, type, name, description) VALUES (1103, 1, 'spp_defrag', 'First defragmenter');
INSERT INTO plugin (id, type, name, description) VALUES (1104, 1, 'spp_anomsensor', 'SPADE');
INSERT INTO plugin (id, type, name, description) VALUES (1105, 1, 'spp_bo', 'Back Orifice');
INSERT INTO plugin (id, type, name, description) VALUES (1106, 1, 'spp_rpc_decode', 'RPC Preprocessor');
INSERT INTO plugin (id, type, name, description) VALUES (1107, 1, 'spp_stream2', '2nd stream preprocessor');
INSERT INTO plugin (id, type, name, description) VALUES (1108, 1, 'spp_stream3', '3rd stream preprocessor');
INSERT INTO plugin (id, type, name, description) VALUES (1109, 1, 'spp_telnet', 'Telnet option decoder');
INSERT INTO plugin (id, type, name, description) VALUES (1110, 1, 'spp_unidecode', 'Unicode decoder');
INSERT INTO plugin (id, type, name, description) VALUES (1111, 1, 'spp_stream4', 'Stream4 preprocessor');
INSERT INTO plugin (id, type, name, description) VALUES (1112, 1, 'spp_arpspoof', 'Arp Spoof detector');
INSERT INTO plugin (id, type, name, description) VALUES (1113, 1, 'spp_frag2', '2nd fragment preprocessor');
INSERT INTO plugin (id, type, name, description) VALUES (1114, 1, 'spp_fnord', 'NOP detector');
INSERT INTO plugin (id, type, name, description) VALUES (1115, 1, 'spp_asn1', 'ASN.1 Validator');
INSERT INTO plugin (id, type, name, description) VALUES (1116, 1, 'snort_decoder', 'Snort Internal Decoder');
INSERT INTO plugin (id, type, name, description) VALUES (1117, 1, 'spp_portscan2', 'Portscan2');
INSERT INTO plugin (id, type, name, description) VALUES (1118, 1, 'spp_conversation', 'Conversation');
INSERT INTO plugin (id, type, name, description) VALUES (1119, 1, 'http_inspect', 'http data check');
INSERT INTO plugin (id, type, name, description) VALUES (1120, 1, 'http_inspect', 'anomalous http server');
INSERT INTO plugin (id, type, name, description) VALUES (1121, 1, 'flow-portscan', 'flow decoder');
INSERT INTO plugin (id, type, name, description) VALUES (1122, 1, 'portscan', 'Portscan decoder');
INSERT INTO plugin (id, type, name, description) VALUES (1123, 1, 'frag3', 'Fragmentation decoder');
INSERT INTO plugin (id, type, name, description) VALUES (1124, 1, 'smtp', 'SMTP preprocessor');
INSERT INTO plugin (id, type, name, description) VALUES (1125, 1, 'ftp_pp', 'FTP preprocessor');
INSERT INTO plugin (id, type, name, description) VALUES (1126, 1, 'telnet_pp', 'Telnet preprocessor');
INSERT INTO plugin (id, type, name, description) VALUES (1128, 1, 'ssh', 'SSH preprocessor');
INSERT INTO plugin (id, type, name, description) VALUES (1129, 1, 'stream5', 'TCP preprocessor');
INSERT INTO plugin (id, type, name, description) VALUES (1130, 1, 'dcerp', 'DCE/RPC server preprocessor');
INSERT INTO plugin (id, type, name, description) VALUES (1131, 1, 'dns', 'DNS preprocessor');
INSERT INTO plugin (id, type, name, description) VALUES (1133, 1, 'dcerpc2', 'DCE/RPC server preprocessor v2');
INSERT INTO plugin (id, type, name, description) VALUES (1134, 1, 'ppm', 'ppm');
INSERT INTO plugin (id, type, name, description) VALUES (1135, 1, 'internal', 'internal');
INSERT INTO plugin (id, type, name, description) VALUES (1137, 1, 'ssp_ssl', 'SSLPP');
INSERT INTO plugin (id, type, name, description) VALUES (1138, 1, 'sensitive_data', 'PII');
INSERT INTO plugin (id, type, name, description) VALUES (1139, 1, 'sensitive_data2', 'sensitive_data2');



--
-- Generators SNORT Plugin Sids
--
-- We will separate this in two parts: first, the plugin sids with special priority and reliability or other thing. After that, the other inserts (generated
-- thanks to scripts/create_sidmap_preprocessors.pl) without priority or reliability. I have separate it here to have a quick look about what's changed or not
-- 1.- Plugin_sids with something special (don't remove unless you're sure!):
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1105, 1, NULL, NULL, 'spp_bo: Back Orifice Traffic Detected', 5, 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1117, 1, NULL, NULL, 'spp_portscan2: Portscan detected!', 3, 3);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1104, 4, 201, NULL, 'Spade: Source used odd dest port', 2, 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1104, 6, 201, NULL, 'Spade: Source used odd dest for port', 3, 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name, priority, reliability) VALUES (1104, 101, 201, NULL, 'Spade: Rare but open dest port used', 3, 1);
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1104, 1, 201, NULL, 'Spade: Closed dest port used');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1104, 3, 201, NULL, 'Spade: Non-live dest used');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1104, 5, 201, NULL, 'Spade: Odd ICMP type/code found');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1104, 102, 201, NULL, 'Spade: Rare dest port used');



-- 2.- plugin_sids directly extracted with scripts/create_sidmap_preprocessors.pl (once removed the entries in the first point)
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1100, 1, NULL, NULL, ' spp_portscan: Portscan Detected');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1100, 2, NULL, NULL, ' spp_portscan: Portscan Status');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1100, 3, NULL, NULL, ' spp_portscan: Portscan Ended');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1101, 1, NULL, NULL, ' spp_minfrag: minfrag alert');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1102, 1, NULL, NULL, ' http_decode: Unicode Attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1102, 2, NULL, NULL, ' http_decode: CGI NULL Byte Attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1102, 3, NULL, NULL, ' http_decode: large method attempted');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1102, 4, NULL, NULL, ' http_decode: missing uri');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1102, 5, NULL, NULL, ' http_decode: double encoding detected');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1102, 6, NULL, NULL, ' http_decode: illegal hex values detected');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1102, 7, NULL, NULL, ' http_decode: overlong character detected');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1103, 1, NULL, NULL, ' spp_defrag: Fragmentation Overflow Detected');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1103, 2, NULL, NULL, ' spp_defrag: Stale Fragments Discarded');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1104, 1, NULL, NULL, ' spp_anomsensor: SPADE Anomaly Threshold Exceeded');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1104, 2, NULL, NULL, ' spp_anomsensor: SPADE Anomaly Threshold Adjusted');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1105, 1, NULL, NULL, ' spp_bo: Back Orifice Traffic Detected');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1105, 2, NULL, NULL, ' spp_bo: Back Orifice Client Traffic Detected');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1105, 3, NULL, NULL, ' spp_bo: Back Orifice Server Traffic Detected');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1105, 4, NULL, NULL, ' spp_bo: Back Orifice Snort Buffer Attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1106, 1, NULL, NULL, ' spp_rpc_decode: Fragmented RPC Records');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1106, 2, NULL, NULL, ' spp_rpc_decode: Multiple Records in one packet');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1106, 3, NULL, NULL, ' spp_rpc_decode: Large RPC Record Fragment');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1106, 4, NULL, NULL, ' spp_rpc_decode: Incomplete RPC segment');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1106, 5, NULL, NULL, ' spp_rpc_decode: Zero-length RPC Fragment');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1110, 1, NULL, NULL, ' spp_unidecode: CGI NULL Attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1110, 2, NULL, NULL, ' spp_unidecode: Directory Traversal');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1110, 3, NULL, NULL, ' spp_unidecode: Unknown Mapping');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1110, 4, NULL, NULL, ' spp_unidecode: Invalid Mapping');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1111, 1, NULL, NULL, ' spp_stream4: Stealth Activity Detected');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1111, 2, NULL, NULL, ' spp_stream4: Evasive Reset Packet');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1111, 3, NULL, NULL, ' spp_stream4: Retransmission');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1111, 4, NULL, NULL, ' spp_stream4: Window Violation');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1111, 5, NULL, NULL, ' spp_stream4: Data on SYN Packet');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1111, 6, NULL, NULL, ' spp_stream4: Full XMAS Stealth Scan');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1111, 7, NULL, NULL, ' spp_stream4: SAPU Stealth Scan');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1111, 8, NULL, NULL, ' spp_stream4: FIN Stealth Scan ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1111, 9, NULL, NULL, ' spp_stream4: NULL Stealth Scan');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1111, 10, NULL, NULL, ' spp_stream4: NMAP XMAS Stealth Scan');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1111, 11, NULL, NULL, ' spp_stream4: VECNA Stealth Scan');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1111, 12, NULL, NULL, ' spp_stream4: NMAP Fingerprint Stateful Detection');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1111, 13, NULL, NULL, ' spp_stream4: SYN FIN Stealth Scan');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1111, 14, NULL, NULL, ' spp_stream4: TCP forward overlap detected');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1111, 15, NULL, NULL, ' spp_stream4: TTL Evasion attempt');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1111, 16, NULL, NULL, ' spp_stream4: Evasive retransmitted data attempt');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1111, 17, NULL, NULL, ' spp_stream4: Evasive retransmitted data with the data split attempt');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1111, 18, NULL, NULL, ' spp_stream4: Multiple acked');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1111, 19, NULL, NULL, ' spp_stream4: Shifting to Emergency Session Mode');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1111, 20, NULL, NULL, ' spp_stream4: Shifting to Suspend Mode');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1111, 21, NULL, NULL, ' spp_stream4: TCP Timestamp option has value of zero');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1111, 22, NULL, NULL, ' spp_stream4: Too many overlapping TCP packets');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1111, 23, NULL, NULL, ' spp_stream4: Packet in established TCP stream missing ACK');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1111, 24, NULL, NULL, ' spp_stream4: Evasive FIN Packet');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1111, 25, NULL, NULL, ' spp_stream4: SYN on established');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1112, 1, NULL, NULL, ' spp_arpspoof: Directed ARP Request');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1112, 2, NULL, NULL, ' spp_arpspoof: Etherframe ARP Mismatch SRC');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1112, 3, NULL, NULL, ' spp_arpspoof: Etherframe ARP Mismatch DST');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1112, 4, NULL, NULL, ' spp_arpspoof: ARP Cache Overwrite Attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1113, 1, NULL, NULL, ' spp_frag2: Oversized Frag');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1113, 2, NULL, NULL, ' spp_frag2: Teardrop/Fragmentation Overlap Attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1113, 3, NULL, NULL, ' spp_frag2: TTL evasion detected');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1113, 4, NULL, NULL, ' spp_frag2: overlap detected');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1113, 5, NULL, NULL, ' spp_frag2: Duplicate first fragments');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1113, 6, NULL, NULL, ' spp_frag2: memcap exceeded');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1113, 7, NULL, NULL, ' spp_frag2: Out of order fragments');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1113, 8, NULL, NULL, ' spp_frag2: IP Options on Fragmented Packet');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1113, 9, NULL, NULL, ' spp_frag2: Shifting to Emegency Session Mode');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1113, 10, NULL, NULL, ' spp_frag2: Shifting to Suspend Mode');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1114, 1, NULL, NULL, ' spp_fnord: Possible Mutated GENERIC NOP Sled detected');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1114, 2, NULL, NULL, ' spp_fnord: Possible Mutated IA32 NOP Sled detected');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1114, 3, NULL, NULL, ' spp_fnord: Possible Mutated HPPA NOP Sled detected');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1114, 4, NULL, NULL, ' spp_fnord: Possible Mutated SPARC NOP Sled detected');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1115, 1, NULL, NULL, ' spp_asn1: Indefinite ASN.1 length encoding');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1115, 2, NULL, NULL, ' spp_asn1: Invalid ASN.1 length encoding');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1115, 3, NULL, NULL, ' spp_asn1: ASN.1 oversized item, possible overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1115, 4, NULL, NULL, ' spp_asn1: ASN.1 spec violation, possible overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1115, 5, NULL, NULL, ' spp_asn1: ASN.1 Attack: Datum length > packet length');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 1, NULL, NULL, ' snort_decoder: WARNING: Not IPv4 datagram!');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 2, NULL, NULL, ' snort_decoder: WARNING: hlen < IP_HEADER_LEN!');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 3, NULL, NULL, ' snort_decoder: WARNING: IP dgm len < IP Hdr len!');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 4, NULL, NULL, ' snort_decoder: WARNING: Bad IPv4 Options');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 5, NULL, NULL, ' snort_decoder: WARNING: Truncated IPv4 Options');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 6, NULL, NULL, ' snort_decoder: WARNING: IP dgm len > captured len!');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 45, NULL, NULL, ' snort_decoder: WARNING: TCP packet len is smaller than 20 bytes!');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 46, NULL, NULL, ' snort_decoder: WARNING: TCP Data Offset is less than 5!');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 47, NULL, NULL, ' snort_decoder: WARNING: TCP Data Offset is longer than payload!');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 54, NULL, NULL, ' snort_decoder: WARNING: Tcp Options found with bad lengths');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 55, NULL, NULL, ' snort_decoder: WARNING: Truncated Tcp Options');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 56, NULL, NULL, ' snort_decoder: WARNING: T/TCP Detected');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 57, NULL, NULL, ' snort_decoder: WARNING: Obsolete TCP options');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 58, NULL, NULL, ' snort_decoder: WARNING: Experimental TCP options');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 59, NULL, NULL, ' snort_decoder: WARNING: TCP Window Scale Option Scale Invalid (> 14)');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 95, NULL, NULL, ' snort_decoder: WARNING: Truncated UDP Header!');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 96, NULL, NULL, ' snort_decoder: WARNING: Invalid UDP header, length field < 8');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 97, NULL, NULL, ' snort_decoder: WARNING: Short UDP packet, length field > payload length');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 98, NULL, NULL, ' snort_decoder: WARNING: Long UDP packet, length field < payload length');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 105, NULL, NULL, ' snort_decoder: WARNING: ICMP Header Truncated!');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 106, NULL, NULL, ' snort_decoder: WARNING: ICMP Timestamp Header Truncated!');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 107, NULL, NULL, ' snort_decoder: WARNING: ICMP Address Header Truncated!');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 108, NULL, NULL, ' snort_decoder: WARNING: Unknown Datagram decoding problem!');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 109, NULL, NULL, ' snort_decoder: WARNING: Truncated ARP Packet!');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 110, NULL, NULL, ' snort_decoder: WARNING: Truncated EAP Header!');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 111, NULL, NULL, ' snort_decoder: WARNING: EAP Key Truncated!');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 112, NULL, NULL, ' snort_decoder: WARNING: EAP Header Truncated!');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 120, NULL, NULL, ' snort_decoder: WARNING: Bad PPPOE frame detected!');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 130, NULL, NULL, ' snort_decoder: WARNING: Bad VLAN Frame!');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 131, NULL, NULL, ' snort_decoder: WARNING: Bad LLC header!');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 132, NULL, NULL, ' snort_decoder: WARNING: Bad Extra LLC Info!');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 133, NULL, NULL, ' snort_decoder: WARNING: Bad 802.11 LLC header!');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 134, NULL, NULL, ' snort_decoder: WARNING: Bad 802.11 Extra LLC Info!');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 140, NULL, NULL, ' snort_decoder: WARNING: Bad Token Ring Header!');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 141, NULL, NULL, ' snort_decoder: WARNING: Bad Token Ring ETHLLC Header!');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 142, NULL, NULL, ' snort_decoder: WARNING: Bad Token Ring MRLEN Header!');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 143, NULL, NULL, ' snort_decoder: WARNING: Bad Token Ring MR Header!');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 150, NULL, NULL, ' snort_decoder: WARNING: Bad Traffic Loopback IP!');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 151, NULL, NULL, ' snort_decoder: WARNING: Bad Traffic Same Src/Dst IP!');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 160, NULL, NULL, ' snort_decoder: WARNING: GRE header length > payload length');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 161, NULL, NULL, ' snort_decoder: WARNING: Multiple encapsulations in packet');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 162, NULL, NULL, ' snort_decoder: WARNING: Invalid GRE version');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 163, NULL, NULL, ' snort_decoder: WARNING: Invalid GRE v.0 header');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 164, NULL, NULL, ' snort_decoder: WARNING: Invalid GRE v.1 PPTP header');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 165, NULL, NULL, ' snort_decoder: WARNING: GRE Trans header length > payload length');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 170, NULL, NULL, ' snort_decoder: WARNING: Bad MPLS Frame');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 171, NULL, NULL, ' snort_decoder: WARNING: MPLS Label 0 Appears in Nonbottom Header');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 172, NULL, NULL, ' snort_decoder: WARNING: MPLS Label 1 Appears in Bottom Header');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 173, NULL, NULL, ' snort_decoder: WARNING: MPLS Label 2 Appears in Nonbottom Header');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 174, NULL, NULL, ' snort_decoder: WARNING: Bad use of label 3');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 175, NULL, NULL, ' snort_decoder: WARNING: MPLS Label 4, 5,.. or 15 Appears in Header');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 176, NULL, NULL, ' snort_decoder: WARNING: Too Many MPLS headers');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 250, NULL, NULL, ' snort_decoder: WARNING: ICMP Original IP Header Truncated!');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 251, NULL, NULL, ' snort_decoder: WARNING: ICMP Original IP Header Not IPv4!');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 252, NULL, NULL, ' snort_decoder: WARNING: ICMP Original Datagram Length < Original IP Header Length!');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 253, NULL, NULL, ' snort_decoder: WARNING: ICMP Original IP Payload < 64 bits!');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 254, NULL, NULL, ' snort_decoder: WARNING: ICMP Original IP Payload > 576 bytes!');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 255, NULL, NULL, ' snort_decoder: WARNING: ICMP Original IP Fragmented and Offset Not 0!');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 270, NULL, NULL, ' snort_decoder: WARNING: IPV6 packet exceeded TTL limit');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 271, NULL, NULL, ' snort_decoder: WARNING: IPv6 header claims to not be IPv6');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 272, NULL, NULL, ' snort_decoder: WARNING: IPV6 truncated extension header');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 273, NULL, NULL, ' snort_decoder: WARNING: IPV6 truncated header');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 274, NULL, NULL, ' snort_decoder: WARNING: IPV6 dgm len < IPV6 Hdr len!');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 275, NULL, NULL, ' snort_decoder: WARNING: IPV6 dgm len > captured len!');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 276, NULL, NULL, ' snort_decoder: WARNING: IPv6 packet with destination address ::0');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 277, NULL, NULL, ' snort_decoder: WARNING: IPv6 packet with multicast source address');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 278, NULL, NULL, ' snort_decoder: WARNING: IPv6 packet with reserved multicast destination address');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 279, NULL, NULL, ' snort_decoder: WARNING: IPv6 header includes an undefined option type');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 280, NULL, NULL, ' snort_decoder: WARNING: IPv6 address includes an unassigned multicast scope value');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 281, NULL, NULL, ' snort_decoder: WARNING: IPv6 header includes an invalid value for the "next header" field');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 282, NULL, NULL, ' snort_decoder: WARNING: IPv6 header includes a routing extension header followed by a hop-by-hop header');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 283, NULL, NULL, ' snort_decoder: WARNING: IPv6 header includes two routing extension headers');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 285, NULL, NULL, ' snort_decoder: WARNING: ICMPv6 packet of type 2 (message too big) with MTU field < 1280');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 286, NULL, NULL, ' snort_decoder: WARNING: ICMPv6 packet of type 1 (destination unreachable) with invalid code field');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 287, NULL, NULL, ' snort_decoder: WARNING: ICMPv6 router solicitation packet with a code not equal to 0');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 288, NULL, NULL, ' snort_decoder: WARNING: ICMPv6 router advertisement packet with a code not equal to 0');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 289, NULL, NULL, ' snort_decoder: WARNING: ICMPv6 router solicitation packet with the reserved field not equal to 0');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 290, NULL, NULL, ' snort_decoder: WARNING: ICMPv6 router advertisement packet with the reachable time field set > 1 hour');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 291, NULL, NULL, ' snort_decoder: WARNING: IPV6 tunneled over IPv4, IPv6 header truncated, possible Linux Kernel attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 292, NULL, NULL, ' snort_decoder: WARNING: IPv6 header has destination options followed by a routing header');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 293, NULL, NULL, ' snort_decoder: WARNING: Two or more IP (v4 and/or v6) encapsulation layers present');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 294, NULL, NULL, ' snort_decoder: WARNING: truncated Encapsulated Security Payload (ESP) header');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 295, NULL, NULL, ' snort_decoder: WARNING: IPv6 header includes an option which is too big for the containing header.');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 296, NULL, NULL, ' snort_decoder: WARNING: IPv6 packet includes out-of-order extension headers');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 400, NULL, NULL, ' snort_decoder: WARNING: XMAS Attack Detected!');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 401, NULL, NULL, ' snort_decoder: WARNING: Nmap XMAS Attack Detected!');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 402, NULL, NULL, ' snort_decoder: WARNING: DOS NAPTHA Vulnerability Detected!');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 403, NULL, NULL, ' snort_decoder: WARNING: Bad Traffic SYN to multicast address');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 404, NULL, NULL, ' snort_decoder: WARNING: IPV4 packet with zero TTL');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 405, NULL, NULL, ' snort_decoder: WARNING: IPV4 packet with bad frag bits (Both MF and DF set)');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 406, NULL, NULL, ' snort_decoder: WARNING: Invalid IPv6 UDP packet, checksum zero');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 407, NULL, NULL, ' snort_decoder: WARNING: IPV4 packet frag offset + length exceed maximum');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 408, NULL, NULL, ' snort_decoder: WARNING: IPV4 packet from 'current net' source address');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 409, NULL, NULL, ' snort_decoder: WARNING: IPV4 packet to 'current net' dest address');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 410, NULL, NULL, ' snort_decoder: WARNING: IPV4 packet from multicast source address');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 411, NULL, NULL, ' snort_decoder: WARNING: IPV4 packet from reserved source address');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 412, NULL, NULL, ' snort_decoder: WARNING: IPV4 packet to reserved dest address');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 413, NULL, NULL, ' snort_decoder: WARNING: IPV4 packet from broadcast source address');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 414, NULL, NULL, ' snort_decoder: WARNING: IPV4 packet to broadcast dest address');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 415, NULL, NULL, ' snort_decoder: WARNING: ICMP4 packet to multicast dest address');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 416, NULL, NULL, ' snort_decoder: WARNING: ICMP4 packet to broadcast dest address');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 417, NULL, NULL, ' snort_decoder: WARNING: ICMP4 source quence');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 418, NULL, NULL, ' snort_decoder: WARNING: ICMP4 type other');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 419, NULL, NULL, ' snort_decoder: WARNING: TCP urgent pointer exceeds payload length or no payload');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 420, NULL, NULL, ' snort_decoder: WARNING: TCP SYN with FIN');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 421, NULL, NULL, ' snort_decoder: WARNING: TCP SYN with RST');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 422, NULL, NULL, ' snort_decoder: WARNING: TCP PDU missing ack for established session');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 423, NULL, NULL, ' snort_decoder: WARNING: TCP has no SYN, ACK, or RST');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 424, NULL, NULL, ' snort_decoder: WARNING: truncated eth header');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 425, NULL, NULL, ' snort_decoder: WARNING: truncated IP4 header');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 426, NULL, NULL, ' snort_decoder: WARNING: truncated ICMP4 header');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 427, NULL, NULL, ' snort_decoder: WARNING: truncated ICMP6 header');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 428, NULL, NULL, ' snort_decoder: WARNING: IPV4 packet below TTL limit');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 429, NULL, NULL, ' snort_decoder: WARNING: IPV6 packet has zero hop limit');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 430, NULL, NULL, ' snort_decoder: WARNING: IPV4 packet both DF and offset set');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 431, NULL, NULL, ' snort_decoder: WARNING: ICMP6 type not decoded');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 432, NULL, NULL, ' snort_decoder: WARNING: ICMP6 packet to multicast address');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 433, NULL, NULL, ' snort_decoder: WARNING: DDOS shaft synflood');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 434, NULL, NULL, ' snort_decoder: WARNING: ICMP PING NMAP');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 435, NULL, NULL, ' snort_decoder: WARNING: ICMP icmpenum v1.1.1');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 436, NULL, NULL, ' snort_decoder: WARNING: ICMP redirect host');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 437, NULL, NULL, ' snort_decoder: WARNING: ICMP redirect net');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 438, NULL, NULL, ' snort_decoder: WARNING: ICMP traceroute ipopts');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 439, NULL, NULL, ' snort_decoder: WARNING: ICMP Source Quench');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 440, NULL, NULL, ' snort_decoder: WARNING: Broadscan Smurf Scanner');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 441, NULL, NULL, ' snort_decoder: WARNING: ICMP Destination Unreachable Communication Administratively Prohibited');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 442, NULL, NULL, ' snort_decoder: WARNING: ICMP Destination Unreachable Communication with Destination Host is Administratively Prohibited');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 443, NULL, NULL, ' snort_decoder: WARNING: ICMP Destination Unreachable Communication with Destination Network is Administratively Prohibited');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 444, NULL, NULL, ' snort_decoder: WARNING: MISC IP option set');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 445, NULL, NULL, ' snort_decoder: WARNING: MISC Large UDP Packet');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 446, NULL, NULL, ' snort_decoder: WARNING: BAD-TRAFFIC TCP port 0 traffic');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 447, NULL, NULL, ' snort_decoder: WARNING: BAD-TRAFFIC UDP port 0 traffic');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 448, NULL, NULL, ' snort_decoder: WARNING: BAD-TRAFFIC IP reserved bit set');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 449, NULL, NULL, ' snort_decoder: WARNING: BAD-TRAFFIC Unassigned/Reserved IP protocol');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 450, NULL, NULL, ' snort_decoder: WARNING: BAD-TRAFFIC Bad IP protocol');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 451, NULL, NULL, ' snort_decoder: WARNING: ICMP PATH MTU denial of service attempt');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1116, 452, NULL, NULL, ' snort_decoder: WARNING: BAD-TRAFFIC linux ICMP header dos attempt');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1117, 1, NULL, NULL, ' spp_portscan2: Portscan detected!');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1118, 1, NULL, NULL, ' spp_conversation: Bad IP protocol!');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1119, 1, NULL, NULL, ' http_inspect: ASCII ENCODING');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1119, 2, NULL, NULL, ' http_inspect: DOUBLE DECODING ATTACK');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1119, 3, NULL, NULL, ' http_inspect: U ENCODING');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1119, 4, NULL, NULL, ' http_inspect: BARE BYTE UNICODE ENCODING');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1119, 5, NULL, NULL, ' http_inspect: BASE36 ENCODING');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1119, 6, NULL, NULL, ' http_inspect: UTF-8 ENCODING');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1119, 7, NULL, NULL, ' http_inspect: IIS UNICODE CODEPOINT ENCODING');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1119, 8, NULL, NULL, ' http_inspect: MULTI_SLASH ENCODING');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1119, 9, NULL, NULL, ' http_inspect: IIS BACKSLASH EVASION');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1119, 10, NULL, NULL, ' http_inspect: SELF DIRECTORY TRAVERSAL');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1119, 11, NULL, NULL, ' http_inspect: DIRECTORY TRAVERSAL');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1119, 12, NULL, NULL, ' http_inspect: APACHE WHITESPACE (TAB)');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1119, 13, NULL, NULL, ' http_inspect: NON-RFC HTTP DELIMITER');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1119, 14, NULL, NULL, ' http_inspect: NON-RFC DEFINED CHAR');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1119, 15, NULL, NULL, ' http_inspect: OVERSIZE REQUEST-URI DIRECTORY');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1119, 16, NULL, NULL, ' http_inspect: OVERSIZE CHUNK ENCODING');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1119, 17, NULL, NULL, ' http_inspect: UNAUTHORIZED PROXY USE DETECTED');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1119, 18, NULL, NULL, ' http_inspect: WEBROOT DIRECTORY TRAVERSAL');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1119, 19, NULL, NULL, ' http_inspect: LONG HEADER');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1119, 20, NULL, NULL, ' http_inspect: MAX HEADERS');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1119, 21, NULL, NULL, ' http_inspect: MULTIPLE CONTENT LENGTH HEADER FIELDS');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1119, 22, NULL, NULL, ' http_inspect: CHUNK SIZE MISMATCH DETECTED');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1119, 23, NULL, NULL, ' http_inspect: INVALID IP IN TRUE-CLIENT-IP/XFF HEADER');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1120, 1, NULL, NULL, ' http_inspect: ANOMALOUS HTTP SERVER ON UNDEFINED HTTP PORT');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1120, 2, NULL, NULL, ' http_inspect: INVALID STATUS CODE IN HTTP RESPONSE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1120, 3, NULL, NULL, ' http_inspect: NO CONTENT-LENGTH OR TRANSFER-ENCODING IN HTTP RESPONSE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1120, 4, NULL, NULL, ' http_inspect: HTTP RESPONSE HAS UTF CHARSET WHICH FAILED TO NORMALIZE');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1120, 5, NULL, NULL, ' http_inspect: HTTP RESPONSE HAS UTF-7 CHARSET');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1121, 1, NULL, NULL, ' flow-portscan: Fixed Scale Scanner Limit Exceeded');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1121, 2, NULL, NULL, ' flow-portscan: Sliding Scale Scanner Limit Exceeded');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1121, 3, NULL, NULL, ' flow-portscan: Fixed Scale Talker Limit Exceeded');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1121, 4, NULL, NULL, ' flow-portscan: Sliding Scale Talker Limit Exceeded');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1122, 1, NULL, NULL, ' portscan: TCP Portscan');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1122, 2, NULL, NULL, ' portscan: TCP Decoy Portscan');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1122, 3, NULL, NULL, ' portscan: TCP Portsweep');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1122, 4, NULL, NULL, ' portscan: TCP Distributed Portscan');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1122, 5, NULL, NULL, ' portscan: TCP Filtered Portscan');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1122, 6, NULL, NULL, ' portscan: TCP Filtered Decoy Portscan');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1122, 7, NULL, NULL, ' portscan: TCP Filtered Portsweep');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1122, 8, NULL, NULL, ' portscan: TCP Filtered Distributed Portscan');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1122, 9, NULL, NULL, ' portscan: IP Protocol Scan');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1122, 10, NULL, NULL, ' portscan: IP Decoy Protocol Scan');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1122, 11, NULL, NULL, ' portscan: IP Protocol Sweep');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1122, 12, NULL, NULL, ' portscan: IP Distributed Protocol Scan');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1122, 13, NULL, NULL, ' portscan: IP Filtered Protocol Scan');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1122, 14, NULL, NULL, ' portscan: IP Filtered Decoy Protocol Scan');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1122, 15, NULL, NULL, ' portscan: IP Filtered Protocol Sweep');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1122, 16, NULL, NULL, ' portscan: IP Filtered Distributed Protocol Scan');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1122, 17, NULL, NULL, ' portscan: UDP Portscan');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1122, 18, NULL, NULL, ' portscan: UDP Decoy Portscan');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1122, 19, NULL, NULL, ' portscan: UDP Portsweep');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1122, 20, NULL, NULL, ' portscan: UDP Distributed Portscan');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1122, 21, NULL, NULL, ' portscan: UDP Filtered Portscan');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1122, 22, NULL, NULL, ' portscan: UDP Filtered Decoy Portscan');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1122, 23, NULL, NULL, ' portscan: UDP Filtered Portsweep');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1122, 24, NULL, NULL, ' portscan: UDP Filtered Distributed Portscan');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1122, 25, NULL, NULL, ' portscan: ICMP Sweep');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1122, 26, NULL, NULL, ' portscan: ICMP Filtered Sweep');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1122, 27, NULL, NULL, ' portscan: Open Port');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1123, 1, NULL, NULL, ' frag3: IP Options on fragmented packet');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1123, 2, NULL, NULL, ' frag3: Teardrop attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1123, 3, NULL, NULL, ' frag3: Short fragment, possible DoS attempt');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1123, 4, NULL, NULL, ' frag3: Fragment packet ends after defragmented packet');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1123, 5, NULL, NULL, ' frag3: Zero-byte fragment');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1123, 6, NULL, NULL, ' frag3: Bad fragment size, packet size is negative');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1123, 7, NULL, NULL, ' frag3: Bad fragment size, packet size is greater than 65536');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1123, 8, NULL, NULL, ' frag3: Fragmentation overlap');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1123, 9, NULL, NULL, ' frag3: IPv6 BSD mbufs remote kernel buffer overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1123, 10, NULL, NULL, ' frag3: Bogus fragmentation packet. Possible BSD attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1123, 11, NULL, NULL, ' frag3: TTL value less than configured minimum, not using for reassembly');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1123, 12, NULL, NULL, ' frag3: Number of overlapping fragments exceed configured limit');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1123, 13, NULL, NULL, ' frag3: Fragments smaller than configured min_fragment_length');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1124, 1, NULL, NULL, ' smtp: Attempted command buffer overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1124, 2, NULL, NULL, ' smtp: Attempted data header buffer overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1124, 3, NULL, NULL, ' smtp: Attempted response buffer overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1124, 4, NULL, NULL, ' smtp: Attempted specific command buffer overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1124, 5, NULL, NULL, ' smtp: Unknown command');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1124, 6, NULL, NULL, ' smtp: Illegal command');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1124, 7, NULL, NULL, ' smtp: Attempted header name buffer overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1124, 8, NULL, NULL, ' smtp: Attempted X-Link2State command buffer overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1125, 1, NULL, NULL, ' ftp_pp: Telnet command on FTP command channel');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1125, 2, NULL, NULL, ' ftp_pp: Invalid FTP command');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1125, 3, NULL, NULL, ' ftp_pp: FTP parameter length overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1125, 4, NULL, NULL, ' ftp_pp: FTP malformed parameter');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1125, 5, NULL, NULL, ' ftp_pp: Possible string format attempt in FTP command/parameter');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1125, 6, NULL, NULL, ' ftp_pp: FTP response length overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1125, 7, NULL, NULL, ' ftp_pp: FTP command channel encrypted');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1125, 8, NULL, NULL, ' ftp_pp: FTP bounce attack');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1125, 9, NULL, NULL, ' ftp_pp: Evasive Telnet command on FTP command channel');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1126, 1, NULL, NULL, ' telnet_pp: Telnet consecutive AYT overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1126, 2, NULL, NULL, ' telnet_pp: Telnet data encrypted');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1126, 3, NULL, NULL, ' telnet_pp: Subnegotiation Begin without matching Subnegotiation End');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1128, 1, NULL, NULL, ' ssh: Gobbles exploit ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1128, 2, NULL, NULL, ' ssh: SSH1 CRC32 exploit ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1128, 3, NULL, NULL, ' ssh: Server version string overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1128, 4, NULL, NULL, ' ssh: Protocol mismatch');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1128, 5, NULL, NULL, ' ssh: Bad message direction');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1128, 6, NULL, NULL, ' ssh: Payload size incorrect for the given payload');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1128, 7, NULL, NULL, ' ssh: Failed to detect SSH version string');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1129, 1, NULL, NULL, ' stream5: SYN on established session');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1129, 2, NULL, NULL, ' stream5: Data on SYN packet');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1129, 3, NULL, NULL, ' stream5: Data sent on stream not accepting data');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1129, 4, NULL, NULL, ' stream5: TCP Timestamp is outside of PAWS window');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1129, 5, NULL, NULL, ' stream5: Bad segment, overlap adjusted size less than/equal 0');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1129, 6, NULL, NULL, ' stream5: Window size (after scaling) larger than policy allows');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1129, 7, NULL, NULL, ' stream5: Limit on number of overlapping TCP packets reached');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1129, 8, NULL, NULL, ' stream5: Data sent on stream after TCP Reset');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1129, 9, NULL, NULL, ' stream5: TCP Client possibly hijacked, different Ethernet Address');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1129, 10, NULL, NULL, ' stream5: TCP Server possibly hijacked, different Ethernet Address');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1129, 11, NULL, NULL, ' stream5: TCP Data with no TCP Flags set ');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1129, 12, NULL, NULL, ' stream5: TCP Small Segment Threshold Exceeded');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1129, 13, NULL, NULL, ' stream5: TCP 4-way handshake detected');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1129, 14, NULL, NULL, ' stream5: TCP Timestamp is missing');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1129, 15, NULL, NULL, ' stream5: Reset outside window');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1129, 16, NULL, NULL, ' stream5: FIN number is greater than prior FIN');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1129, 17, NULL, NULL, ' stream5: ACK number is greater than prior FIN');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1129, 18, NULL, NULL, ' stream5: Data sent on stream after TCP Reset received');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1129, 19, NULL, NULL, ' stream5: TCP window closed before receiving data');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1130, 1, NULL, NULL, ' dcerpc: Maximum memory usage reached');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1131, 1, NULL, NULL, ' dns: Obsolete DNS RData Type');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1131, 2, NULL, NULL, ' dns: Experimental DNS RData Type');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1131, 3, NULL, NULL, ' dns: Client RData TXT Overflow');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1133, 1, NULL, NULL, ' dcerpc2: Memory cap exceeded');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1133, 2, NULL, NULL, ' dcerpc2: SMB - Bad NetBIOS Session Service session type');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1133, 3, NULL, NULL, ' dcerpc2: SMB - Bad SMB message type');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1133, 4, NULL, NULL, ' dcerpc2: SMB - Bad SMB Id (not "\xffSMB" for SMB1 or not "\xfeSMB" for SMB2)');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1133, 5, NULL, NULL, ' dcerpc2: SMB - Bad word count or structure size for command');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1133, 6, NULL, NULL, ' dcerpc2: SMB - Bad byte count for command');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1133, 7, NULL, NULL, ' dcerpc2: SMB - Bad format type for command');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1133, 8, NULL, NULL, ' dcerpc2: SMB - Bad AndX or data offset in command');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1133, 9, NULL, NULL, ' dcerpc2: SMB - Zero total data count in command');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1133, 10, NULL, NULL, ' dcerpc2: SMB - NetBIOS data length less than SMB header length');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1133, 11, NULL, NULL, ' dcerpc2: SMB - Remaining NetBIOS data length less than command length');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1133, 12, NULL, NULL, ' dcerpc2: SMB - Remaining NetBIOS data length less than command byte count');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1133, 13, NULL, NULL, ' dcerpc2: SMB - Remaining NetBIOS data length less than command data size');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1133, 14, NULL, NULL, ' dcerpc2: SMB - Remaining total data count less than this command data size');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1133, 15, NULL, NULL, ' dcerpc2: SMB - Total data sent greater than command total data expected');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1133, 16, NULL, NULL, ' dcerpc2: SMB - Byte count less than command data size');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1133, 17, NULL, NULL, ' dcerpc2: SMB - Invalid command data size for byte count');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1133, 18, NULL, NULL, ' dcerpc2: SMB - Excessive Tree Connect requests with pending Tree Connect responses');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1133, 19, NULL, NULL, ' dcerpc2: SMB - Excessive Read requests with pending Read responses');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1133, 20, NULL, NULL, ' dcerpc2: SMB - Excessive command chaining');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1133, 21, NULL, NULL, ' dcerpc2: SMB - Multiple chained login requests');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1133, 22, NULL, NULL, ' dcerpc2: SMB - Multiple chained tree connect requests');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1133, 23, NULL, NULL, ' dcerpc2: SMB - Chained/Compounded login followed by logoff');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1133, 24, NULL, NULL, ' dcerpc2: SMB - Chained/Compounded tree connect followed by tree disconnect');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1133, 25, NULL, NULL, ' dcerpc2: SMB - Chained/Compounded open pipe followed by close pipe');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1133, 26, NULL, NULL, ' dcerpc2: SMB - Invalid share access');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1133, 27, NULL, NULL, ' dcerpc2: Connection-oriented DCE/RPC - Invalid major version');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1133, 28, NULL, NULL, ' dcerpc2: Connection-oriented DCE/RPC - Invalid minor version');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1133, 29, NULL, NULL, ' dcerpc2: Connection-oriented DCE/RPC - Invalid pdu type');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1133, 30, NULL, NULL, ' dcerpc2: Connection-oriented DCE/RPC - Fragment length less than header size');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1133, 31, NULL, NULL, ' dcerpc2: Connection-oriented DCE/RPC - Remaining fragment length less than size needed');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1133, 32, NULL, NULL, ' dcerpc2: Connection-oriented DCE/RPC - No context items specified');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1133, 33, NULL, NULL, ' dcerpc2: Connection-oriented DCE/RPC - No transfer syntaxes specified');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1133, 34, NULL, NULL, ' dcerpc2: Connection-oriented DCE/RPC - Fragment length on non-last fragment less than maximum negotiated fragment transmit size for client');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1133, 35, NULL, NULL, ' dcerpc2: Connection-oriented DCE/RPC - Fragment length greater than maximum negotiated fragment transmit size');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1133, 36, NULL, NULL, ' dcerpc2: Connection-oriented DCE/RPC - Alter Context byte order different from Bind');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1133, 37, NULL, NULL, ' dcerpc2: Connection-oriented DCE/RPC - Call id of non first/last fragment different from call id established for fragmented request');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1133, 38, NULL, NULL, ' dcerpc2: Connection-oriented DCE/RPC - Opnum of non first/last fragment different from opnum established for fragmented request');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1133, 39, NULL, NULL, ' dcerpc2: Connection-oriented DCE/RPC - Context id of non first/last fragment different from context id established for fragmented request');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1133, 40, NULL, NULL, ' dcerpc2: Connectionless DCE/RPC - Invalid major version');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1133, 41, NULL, NULL, ' dcerpc2: Connectionless DCE/RPC - Invalid pdu type');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1133, 42, NULL, NULL, ' dcerpc2: Connectionless DCE/RPC - Data length less than header size');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1133, 43, NULL, NULL, ' dcerpc2: Connectionless DCE/RPC - Bad sequence number');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1133, 44, NULL, NULL, ' dcerpc2: SMB - Invalid SMB version 1 seen');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1133, 45, NULL, NULL, ' dcerpc2: SMB - Invalid SMB version 2 seen');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1133, 46, NULL, NULL, ' dcerpc2: SMB - Invalid user, tree connect, file binding');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1133, 47, NULL, NULL, ' dcerpc2: SMB - Excessive command compounding');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1134, 1, NULL, NULL, ' ppm: rule tree disabled');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1134, 2, NULL, NULL, ' ppm: rule tree enabled');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1135, 1, NULL, NULL, ' internal: syn received');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1135, 2, NULL, NULL, ' internal: session established');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1135, 3, NULL, NULL, ' internal: session cleared');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1137, 1, NULL, NULL, ' ssp_ssl: Invalid Client HELLO after Server HELLO Detected');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1137, 2, NULL, NULL, ' ssp_ssl: Invalid Server HELLO without Client HELLO Detected');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1138, 2, NULL, NULL, ' sensitive_data: sensitive data - Credit card numbers');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1138, 3, NULL, NULL, ' sensitive_data: sensitive data - U.S. social security numbers with dashes');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1138, 4, NULL, NULL, ' sensitive_data: sensitive data - U.S. social security numbers without dashes');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1138, 5, NULL, NULL, ' sensitive_data: sensitive data - eMail addresses');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1138, 6, NULL, NULL, ' sensitive_data: sensitive data - U.S. phone numbers');
INSERT IGNORE INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1139, 1, NULL, NULL, ' sensitive_data: sensitive data global threshold exceeded');
