-- Wmi-Windows: for Windows
-- plugin_id: 1802
--

DELETE FROM plugin WHERE id = "1802";
DELETE FROM plugin_sid where plugin_id = "1802";

INSERT INTO plugin (id, type, name, description) VALUES (1802, 1, 'wmi-system-logger', 'Wmi-Windows: Agent for Windows');

INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 512, NULL, NULL, 'Wmi-Windows:: Windows NT is starting up');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 513, NULL, NULL, 'Wmi-Windows:: Windows is shutting down');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 514, NULL, NULL, 'Wmi-Windows:: An authentication package has been loaded by the Local Security Authority');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 515, NULL, NULL, 'Wmi-Windows:: A trusted logon process has registered with the Local Security Authority');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 516, NULL, NULL, 'Wmi-Windows:: Internal resources allocated for the queuing of audit messages have been exhausted, leading to the loss of some audits');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 517, NULL, NULL, 'Wmi-Windows:: The audit log was cleared');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 518, NULL, NULL, 'Wmi-Windows:: A notification package has been loaded by the Security Account Manager');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 519, NULL, NULL, 'Wmi-Windows:: A process is using an invalid local procedure call (LPC) port');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 520, NULL, NULL, 'Wmi-Windows:: The system time was changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 521, NULL, NULL, 'Wmi-Windows:: Unable to log events to security log');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 528, NULL, NULL, 'Wmi-Windows:: Successful Logon');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 529, NULL, NULL, 'Wmi-Windows:: Logon Failure - Unknown user name or bad password');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 530, NULL, NULL, 'Wmi-Windows:: Logon Failure - Account logon time restriction violation');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 531, NULL, NULL, 'Wmi-Windows:: Logon Failure - Account currently disabled');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 532, NULL, NULL, 'Wmi-Windows:: Logon Failure - The specified user account has expired');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 533, NULL, NULL, 'Wmi-Windows:: Logon Failure - User not allowed to logon at this computer');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 534, NULL, NULL, 'Wmi-Windows:: Logon Failure - The user has not been granted the requested logon type at this machine');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 535, NULL, NULL, 'Wmi-Windows:: Logon Failure - The specified accounts password has expired');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 536, NULL, NULL, 'Wmi-Windows:: Logon Failure - The NetLogon component is not active');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 537, NULL, NULL, 'Wmi-Windows:: Logon failure - The logon attempt failed for other reasons.');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 538, NULL, NULL, 'Wmi-Windows:: User Logoff');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 539, NULL, NULL, 'Wmi-Windows:: Logon Failure - Account locked out');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 540, NULL, NULL, 'Wmi-Windows:: Successful Network Logon');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 541, NULL, NULL, 'Wmi-Windows:: IKE security association established');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 542, NULL, NULL, 'Wmi-Windows:: IKE security association ended.');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 545, NULL, NULL, 'Wmi-Windows:: IKE peer authentication failed.');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 546, NULL, NULL, 'Wmi-Windows:: IKE security association establishment failed because peer sent invalid proposal.');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 547, NULL, NULL, 'Wmi-Windows:: IKE security association negotiation failed.');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 548, NULL, NULL, 'Wmi-Windows:: Logon Failure.');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 551, NULL, NULL, 'Wmi-Windows:: User initiated logoff');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 552, NULL, NULL, 'Wmi-Windows:: Logon attempt using explicit credentials');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 560, NULL, NULL, 'Wmi-Windows:: Object Open');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 561, NULL, NULL, 'Wmi-Windows:: Handle Allocated');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 562, NULL, NULL, 'Wmi-Windows:: Handle Closed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 563, NULL, NULL, 'Wmi-Windows:: Object Open for Delete');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 564, NULL, NULL, 'Wmi-Windows:: Object Deleted');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 565, NULL, NULL, 'Wmi-Windows:: Object Open (Active Directory)');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 566, NULL, NULL, 'Wmi-Windows:: Object Operation (W3 Active Directory)');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 567, NULL, NULL, 'Wmi-Windows:: Object Access Attempt');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 568, NULL, NULL, 'Wmi-Windows:: Hard link creation attempt');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 570, NULL, NULL, 'Wmi-Windows:: Application operation attempt');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 576, NULL, NULL, 'Wmi-Windows:: Special privileges assigned to new logon');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 577, NULL, NULL, 'Wmi-Windows:: Privileged Service Called');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 578, NULL, NULL, 'Wmi-Windows:: Privileged object operation');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 592, NULL, NULL, 'Wmi-Windows:: A new process has been created');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 593, NULL, NULL, 'Wmi-Windows:: A process has exited');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 594, NULL, NULL, 'Wmi-Windows:: A handle to an object has been duplicated');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 595, NULL, NULL, 'Wmi-Windows:: Indirect access to an object has been obtained');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 596, NULL, NULL, 'Wmi-Windows:: Backup of data protection master key. ');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 597, NULL, NULL, 'Wmi-Windows:: Recovery of data protection master key.');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 598, NULL, NULL, 'Wmi-Windows:: Protection of auditable protected data. ');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 599, NULL, NULL, 'Wmi-Windows:: Unprotection of auditable protected data'); 
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 600, NULL, NULL, 'Wmi-Windows:: A process was assigned a primary token');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 601, NULL, NULL, 'Wmi-Windows:: Attempt to install service');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 602, NULL, NULL, 'Wmi-Windows:: Scheduled Task created');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 608, NULL, NULL, 'Wmi-Windows:: User Right Assigned');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 609, NULL, NULL, 'Wmi-Windows:: User Right Removed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 610, NULL, NULL, 'Wmi-Windows:: New Trusted Domain');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 611, NULL, NULL, 'Wmi-Windows:: Removing Trusted Domain');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 612, NULL, NULL, 'Wmi-Windows:: Audit Policy Change');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 613, NULL, NULL, 'Wmi-Windows:: IPSec policy agent started');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 614, NULL, NULL, 'Wmi-Windows:: IPSec policy agent disabled');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 615, NULL, NULL, 'Wmi-Windows:: IPSEC PolicyAgent Service');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 616, NULL, NULL, 'Wmi-Windows:: IPSec policy agent encountered a potentially serious failure.');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 617, NULL, NULL, 'Wmi-Windows:: Kerberos Policy Changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 618, NULL, NULL, 'Wmi-Windows:: Encrypted Data Recovery Policy Changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 619, NULL, NULL, 'Wmi-Windows:: Quality of Service Policy Changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 620, NULL, NULL, 'Wmi-Windows:: Trusted Domain Information Modified');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 621, NULL, NULL, 'Wmi-Windows:: System Security Access Granted');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 622, NULL, NULL, 'Wmi-Windows:: System Security Access Removed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 623, NULL, NULL, 'Wmi-Windows:: Per User Audit Policy was refreshed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 624, NULL, NULL, 'Wmi-Windows:: User Account Created');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 625, NULL, NULL, 'Wmi-Windows:: User Account Type Changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 626, NULL, NULL, 'Wmi-Windows:: User Account Enabled');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 627, NULL, NULL, 'Wmi-Windows:: Change Password Attempt');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 628, NULL, NULL, 'Wmi-Windows:: User Account password set');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 629, NULL, NULL, 'Wmi-Windows:: User Account Disabled');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 630, NULL, NULL, 'Wmi-Windows:: User Account Deleted');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 631, NULL, NULL, 'Wmi-Windows:: Security Enabled Global Group Created');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 632, NULL, NULL, 'Wmi-Windows:: Security Enabled Global Group Member Added');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 633, NULL, NULL, 'Wmi-Windows:: Security Enabled Global Group Member Removed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 634, NULL, NULL, 'Wmi-Windows:: Security Enabled Global Group Deleted');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 635, NULL, NULL, 'Wmi-Windows:: Security Enabled Local Group Created');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 636, NULL, NULL, 'Wmi-Windows:: Security Enabled Local Group Member Added');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 637, NULL, NULL, 'Wmi-Windows:: Security Enabled Local Group Member Removed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 638, NULL, NULL, 'Wmi-Windows:: Security Enabled Local Group Deleted');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 639, NULL, NULL, 'Wmi-Windows:: Security Enabled Local Group Changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 640, NULL, NULL, 'Wmi-Windows:: General Account Database Change');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 641, NULL, NULL, 'Wmi-Windows:: Security Enabled Global Group Changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 642, NULL, NULL, 'Wmi-Windows:: User Account Changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 643, NULL, NULL, 'Wmi-Windows:: Domain Policy Changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 644, NULL, NULL, 'Wmi-Windows:: User Account Locked Out');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 645, NULL, NULL, 'Wmi-Windows:: Computer Account Created');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 646, NULL, NULL, 'Wmi-Windows:: Computer Account Changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 647, NULL, NULL, 'Wmi-Windows:: Computer Account Deleted');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 648, NULL, NULL, 'Wmi-Windows:: Security Disabled Local Group Created');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 649, NULL, NULL, 'Wmi-Windows:: Security Disabled Local Group Changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 650, NULL, NULL, 'Wmi-Windows:: Security Disabled Local Group Member Added');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 651, NULL, NULL, 'Wmi-Windows:: Security Disabled Local Group Member Removed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 652, NULL, NULL, 'Wmi-Windows:: Security Disabled Local Group Deleted');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 653, NULL, NULL, 'Wmi-Windows:: Security Disabled Global Group Created');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 654, NULL, NULL, 'Wmi-Windows:: Security Disabled Global Group Changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 655, NULL, NULL, 'Wmi-Windows:: Security Disabled Global Group Member Added');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 656, NULL, NULL, 'Wmi-Windows:: Security Disabled Global Group Member Removed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 657, NULL, NULL, 'Wmi-Windows:: Security Disabled Global Group Deleted');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 658, NULL, NULL, 'Wmi-Windows:: Security Enabled Universal Group Created');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 659, NULL, NULL, 'Wmi-Windows:: Security Enabled Universal Group Changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 660, NULL, NULL, 'Wmi-Windows:: Security Enabled Universal Group Member Added');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 661, NULL, NULL, 'Wmi-Windows:: Security Enabled Universal Group Member Removed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 662, NULL, NULL, 'Wmi-Windows:: Security Enabled Universal Group Deleted');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 663, NULL, NULL, 'Wmi-Windows:: Security Disabled Universal Group Created');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 664, NULL, NULL, 'Wmi-Windows:: Security Disabled Universal Group Changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 665, NULL, NULL, 'Wmi-Windows:: Security Disabled Universal Group Member Added');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 666, NULL, NULL, 'Wmi-Windows:: Security Disabled Universal Group Member Removed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 667, NULL, NULL, 'Wmi-Windows:: Security Disabled Universal Group Deleted');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 668, NULL, NULL, 'Wmi-Windows:: Group Type Changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 669, NULL, NULL, 'Wmi-Windows:: Add SID History');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 670, NULL, NULL, 'Wmi-Windows:: Add SID History');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 671, NULL, NULL, 'Wmi-Windows:: User Account Unlocked');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 672, NULL, NULL, 'Wmi-Windows:: Authentication Ticket Granted');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 673, NULL, NULL, 'Wmi-Windows:: Service Ticket Granted');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 674, NULL, NULL, 'Wmi-Windows:: Ticket Granted Renewed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 675, NULL, NULL, 'Wmi-Windows:: Pre-authentication failed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 676, NULL, NULL, 'Wmi-Windows:: Authentication Ticket Request Failed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 677, NULL, NULL, 'Wmi-Windows:: Service Ticket Request Failed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 678, NULL, NULL, 'Wmi-Windows:: Account Mapped for Logon by');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 679, NULL, NULL, 'Wmi-Windows:: The name: %2 could not be mapped for logon by: %1');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 680, NULL, NULL, 'Wmi-Windows:: Account Used for Logon by');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 681, NULL, NULL, 'Wmi-Windows:: The logon to account: %2 by: %1 from workstation: %3 failed.');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 682, NULL, NULL, 'Wmi-Windows:: Session reconnected to winstation');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 683, NULL, NULL, 'Wmi-Windows:: Session disconnected from winstation');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 684, NULL, NULL, 'Wmi-Windows:: Set ACLs of members in administrators groups');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 685, NULL, NULL, 'Wmi-Windows:: Account Name Changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 686, NULL, NULL, 'Wmi-Windows:: Password of the following user accessed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 687, NULL, NULL, 'Wmi-Windows:: Basic Application Group Created');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 688, NULL, NULL, 'Wmi-Windows:: Basic Application Group Changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 689, NULL, NULL, 'Wmi-Windows:: Basic Application Group Member Added');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 690, NULL, NULL, 'Wmi-Windows:: Basic Application Group Member Removed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 691, NULL, NULL, 'Wmi-Windows:: Basic Application Group Non-Member Added');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 692, NULL, NULL, 'Wmi-Windows:: Basic Application Group Non-Member Removed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 693, NULL, NULL, 'Wmi-Windows:: Basic Application Group Deleted');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 694, NULL, NULL, 'Wmi-Windows:: LDAP Query Group Created');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 695, NULL, NULL, 'Wmi-Windows:: LDAP Query Group Changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 696, NULL, NULL, 'Wmi-Windows:: LDAP Query Group Deleted');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 697, NULL, NULL, 'Wmi-Windows:: Password Policy Checking API is called');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 698, NULL, NULL, 'Wmi-Windows:: An attempt to set the Directory Services Restore Mode administrator password has been made.');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 792, NULL, NULL, 'Wmi-Windows:: Certificate Services denied a certificate request.');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 806, NULL, NULL, 'Wmi-Windows:: Per User Audit Policy was refreshed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 807, NULL, NULL, 'Wmi-Windows:: Per user auditing policy set for user');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 808, NULL, NULL, 'Wmi-Windows:: A security event source has attempted to register.');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 835, NULL, NULL, 'Wmi-Windows:: Destination DRA');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 836, NULL, NULL, 'Wmi-Windows:: Destination DRA');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 837, NULL, NULL, 'Wmi-Windows:: Destination DRA');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 848, NULL, NULL, 'Wmi-Windows:: The following policy was active when the Windows Firewall started. ');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 849, NULL, NULL, 'Wmi-Windows:: An application was listed as an exception when the Windows Firewall started. ');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 850, NULL, NULL, 'Wmi-Windows:: A port was listed as an exception when the Windows Firewall started. ');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 852, NULL, NULL, 'Wmi-Windows:: A change has been made to the Windows Firewall port exception list.');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 853, NULL, NULL, 'Wmi-Windows:: The Windows Firewall operational mode has changed.');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 854, NULL, NULL, 'Wmi-Windows:: The Windows Firewall logging settings have changed.');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 860, NULL, NULL, 'Wmi-Windows:: The Windows Firewall has switched the active policy profile.');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 861, NULL, NULL, 'Wmi-Windows:: The Windows Firewall has detected an application listening for incoming traffic.');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 1100, NULL, NULL, 'Wmi-Windows:: The event logging service has shut down');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 1101, NULL, NULL, 'Wmi-Windows:: Audit events have been dropped by the transport.');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 1102, NULL, NULL, 'Wmi-Windows:: The audit log was cleared');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 1104, NULL, NULL, 'Wmi-Windows:: The security Log is now full');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 1105, NULL, NULL, 'Wmi-Windows:: Event log automatic backup');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 1108, NULL, NULL, 'Wmi-Windows:: The event logging service encountered an error');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4608, NULL, NULL, 'Wmi-Windows:: Windows is starting up');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4609, NULL, NULL, 'Wmi-Windows:: Windows is shutting down');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4610, NULL, NULL, 'Wmi-Windows:: An authentication package has been loaded by the Local Security Authority');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4611, NULL, NULL, 'Wmi-Windows:: A trusted logon process has been registered with the Local Security Authority');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4612, NULL, NULL, 'Wmi-Windows:: Internal resources allocated for the queuing of audit messages have been exhausted, leading to the loss of some audits.');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4614, NULL, NULL, 'Wmi-Windows:: A notification package has been loaded by the Security Account Manager.');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4615, NULL, NULL, 'Wmi-Windows:: Invalid use of LPC port');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4616, NULL, NULL, 'Wmi-Windows:: The system time was changed.');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4618, NULL, NULL, 'Wmi-Windows:: A monitored security event pattern has occurred');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4621, NULL, NULL, 'Wmi-Windows:: Administrator recovered system from CrashOnAuditFail');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4622, NULL, NULL, 'Wmi-Windows:: A security package has been loaded by the Local Security Authority.');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4624, NULL, NULL, 'Wmi-Windows:: An account was successfully logged on');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4625, NULL, NULL, 'Wmi-Windows:: An account failed to log on');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4634, NULL, NULL, 'Wmi-Windows:: An account was logged off');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4646, NULL, NULL, 'Wmi-Windows:: 1.00%');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4647, NULL, NULL, 'Wmi-Windows:: User initiated logoff');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4648, NULL, NULL, 'Wmi-Windows:: A logon was attempted using explicit credentials');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4649, NULL, NULL, 'Wmi-Windows:: A replay attack was detected');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4650, NULL, NULL, 'Wmi-Windows:: An IPsec Main Mode security association was established');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4651, NULL, NULL, 'Wmi-Windows:: An IPsec Main Mode security association was established');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4652, NULL, NULL, 'Wmi-Windows:: An IPsec Main Mode negotiation failed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4653, NULL, NULL, 'Wmi-Windows:: An IPsec Main Mode negotiation failed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4654, NULL, NULL, 'Wmi-Windows:: An IPsec Quick Mode negotiation failed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4655, NULL, NULL, 'Wmi-Windows:: An IPsec Main Mode security association ended');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4656, NULL, NULL, 'Wmi-Windows:: A handle to an object was requested');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4657, NULL, NULL, 'Wmi-Windows:: A registry value was modified');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4658, NULL, NULL, 'Wmi-Windows:: The handle to an object was closed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4659, NULL, NULL, 'Wmi-Windows:: A handle to an object was requested with intent to delete');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4660, NULL, NULL, 'Wmi-Windows:: An object was deleted');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4661, NULL, NULL, 'Wmi-Windows:: A handle to an object was requested');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4662, NULL, NULL, 'Wmi-Windows:: An operation was performed on an object');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4663, NULL, NULL, 'Wmi-Windows:: An attempt was made to access an object');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4664, NULL, NULL, 'Wmi-Windows:: An attempt was made to create a hard link');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4665, NULL, NULL, 'Wmi-Windows:: An attempt was made to create an application client context.');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4666, NULL, NULL, 'Wmi-Windows:: An application attempted an operation');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4667, NULL, NULL, 'Wmi-Windows:: An application client context was deleted');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4668, NULL, NULL, 'Wmi-Windows:: An application was initialized');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4670, NULL, NULL, 'Wmi-Windows:: Permissions on an object were changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4671, NULL, NULL, 'Wmi-Windows:: An application attempted to access a blocked ordinal through the TBS');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4672, NULL, NULL, 'Wmi-Windows:: Special privileges assigned to new logon');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4673, NULL, NULL, 'Wmi-Windows:: A privileged service was called');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4674, NULL, NULL, 'Wmi-Windows:: An operation was attempted on a privileged object');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4675, NULL, NULL, 'Wmi-Windows:: SIDs were filtered');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4685, NULL, NULL, 'Wmi-Windows:: The state of a transaction has changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4688, NULL, NULL, 'Wmi-Windows:: A new process has been created');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4689, NULL, NULL, 'Wmi-Windows:: A process has exited');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4690, NULL, NULL, 'Wmi-Windows:: An attempt was made to duplicate a handle to an object');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4691, NULL, NULL, 'Wmi-Windows:: Indirect access to an object was requested');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4692, NULL, NULL, 'Wmi-Windows:: Backup of data protection master key was attempted');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4693, NULL, NULL, 'Wmi-Windows:: Recovery of data protection master key was attempted');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4694, NULL, NULL, 'Wmi-Windows:: Protection of auditable protected data was attempted');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4695, NULL, NULL, 'Wmi-Windows:: Unprotection of auditable protected data was attempted');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4696, NULL, NULL, 'Wmi-Windows:: A primary token was assigned to process');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4697, NULL, NULL, 'Wmi-Windows:: A service was installed in the system');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4698, NULL, NULL, 'Wmi-Windows:: A scheduled task was created');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4699, NULL, NULL, 'Wmi-Windows:: A scheduled task was deleted');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4700, NULL, NULL, 'Wmi-Windows:: A scheduled task was enabled');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4701, NULL, NULL, 'Wmi-Windows:: A scheduled task was disabled');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4702, NULL, NULL, 'Wmi-Windows:: A scheduled task was updated');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4704, NULL, NULL, 'Wmi-Windows:: A user right was assigned');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4705, NULL, NULL, 'Wmi-Windows:: A user right was removed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4706, NULL, NULL, 'Wmi-Windows:: A new trust was created to a domain');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4707, NULL, NULL, 'Wmi-Windows:: A trust to a domain was removed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4709, NULL, NULL, 'Wmi-Windows:: IPsec Services was started');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4710, NULL, NULL, 'Wmi-Windows:: IPsec Services was disabled');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4711, NULL, NULL, 'Wmi-Windows:: PAStore Engine (1%)');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4712, NULL, NULL, 'Wmi-Windows:: IPsec Services encountered a potentially serious failure');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4713, NULL, NULL, 'Wmi-Windows:: Kerberos policy was changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4714, NULL, NULL, 'Wmi-Windows:: Encrypted data recovery policy was changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4715, NULL, NULL, 'Wmi-Windows:: The audit policy (SACL) on an object was changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4716, NULL, NULL, 'Wmi-Windows:: Trusted domain information was modified');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4717, NULL, NULL, 'Wmi-Windows:: System security access was granted to an account');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4718, NULL, NULL, 'Wmi-Windows:: System security access was removed from an account');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4719, NULL, NULL, 'Wmi-Windows:: System audit policy was changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4720, NULL, NULL, 'Wmi-Windows:: A user account was created');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4722, NULL, NULL, 'Wmi-Windows:: A user account was enabled');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4723, NULL, NULL, 'Wmi-Windows:: An attempt was made to change an accounts password');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4724, NULL, NULL, 'Wmi-Windows:: An attempt was made to reset an accounts password');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4725, NULL, NULL, 'Wmi-Windows:: A user account was disabled');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4726, NULL, NULL, 'Wmi-Windows:: A user account was deleted');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4727, NULL, NULL, 'Wmi-Windows:: A security-enabled global group was created');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4728, NULL, NULL, 'Wmi-Windows:: A member was added to a security-enabled global group');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4729, NULL, NULL, 'Wmi-Windows:: A member was removed from a security-enabled global group');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4730, NULL, NULL, 'Wmi-Windows:: A security-enabled global group was deleted');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4731, NULL, NULL, 'Wmi-Windows:: A security-enabled local group was created');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4732, NULL, NULL, 'Wmi-Windows:: A member was added to a security-enabled local group');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4733, NULL, NULL, 'Wmi-Windows:: A member was removed from a security-enabled local group');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4734, NULL, NULL, 'Wmi-Windows:: A security-enabled local group was deleted');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4735, NULL, NULL, 'Wmi-Windows:: A security-enabled local group was changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4737, NULL, NULL, 'Wmi-Windows:: A security-enabled global group was changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4738, NULL, NULL, 'Wmi-Windows:: A user account was changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4739, NULL, NULL, 'Wmi-Windows:: Domain Policy was changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4740, NULL, NULL, 'Wmi-Windows:: A user account was locked out');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4741, NULL, NULL, 'Wmi-Windows:: A computer account was created');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4742, NULL, NULL, 'Wmi-Windows:: A computer account was changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4743, NULL, NULL, 'Wmi-Windows:: A computer account was deleted');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4744, NULL, NULL, 'Wmi-Windows:: A security-disabled local group was created');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4745, NULL, NULL, 'Wmi-Windows:: A security-disabled local group was changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4746, NULL, NULL, 'Wmi-Windows:: A member was added to a security-disabled local group');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4747, NULL, NULL, 'Wmi-Windows:: A member was removed from a security-disabled local group');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4748, NULL, NULL, 'Wmi-Windows:: A security-disabled local group was deleted');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4749, NULL, NULL, 'Wmi-Windows:: A security-disabled global group was created');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4750, NULL, NULL, 'Wmi-Windows:: A security-disabled global group was changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4751, NULL, NULL, 'Wmi-Windows:: A member was added to a security-disabled global group');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4752, NULL, NULL, 'Wmi-Windows:: A member was removed from a security-disabled global group');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4753, NULL, NULL, 'Wmi-Windows:: A security-disabled global group was deleted');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4754, NULL, NULL, 'Wmi-Windows:: A security-enabled universal group was created');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4755, NULL, NULL, 'Wmi-Windows:: A security-enabled universal group was changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4756, NULL, NULL, 'Wmi-Windows:: A member was added to a security-enabled universal group');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4757, NULL, NULL, 'Wmi-Windows:: A member was removed from a security-enabled universal group');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4758, NULL, NULL, 'Wmi-Windows:: A security-enabled universal group was deleted');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4759, NULL, NULL, 'Wmi-Windows:: A security-disabled universal group was created');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4760, NULL, NULL, 'Wmi-Windows:: A security-disabled universal group was changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4761, NULL, NULL, 'Wmi-Windows:: A member was added to a security-disabled universal group');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4762, NULL, NULL, 'Wmi-Windows:: A member was removed from a security-disabled universal group');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4763, NULL, NULL, 'Wmi-Windows:: A security-disabled universal group was deleted');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4764, NULL, NULL, 'Wmi-Windows:: A groups type was changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4765, NULL, NULL, 'Wmi-Windows:: SID History was added to an account');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4766, NULL, NULL, 'Wmi-Windows:: An attempt to add SID History to an account failed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4767, NULL, NULL, 'Wmi-Windows:: A user account was unlocked');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4768, NULL, NULL, 'Wmi-Windows:: A Kerberos authentication ticket (TGT) was requested');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4769, NULL, NULL, 'Wmi-Windows:: A Kerberos service ticket was requested');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4770, NULL, NULL, 'Wmi-Windows:: A Kerberos service ticket was renewed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4771, NULL, NULL, 'Wmi-Windows:: Kerberos pre-authentication failed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4772, NULL, NULL, 'Wmi-Windows:: A Kerberos authentication ticket request failed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4773, NULL, NULL, 'Wmi-Windows:: A Kerberos service ticket request failed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4774, NULL, NULL, 'Wmi-Windows:: An account was mapped for logon');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4775, NULL, NULL, 'Wmi-Windows:: An account could not be mapped for logon');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4776, NULL, NULL, 'Wmi-Windows:: The domain controller attempted to validate the credentials for an account');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4777, NULL, NULL, 'Wmi-Windows:: The domain controller failed to validate the credentials for an account');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4778, NULL, NULL, 'Wmi-Windows:: A session was reconnected to a Window Station');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4779, NULL, NULL, 'Wmi-Windows:: A session was disconnected from a Window Station');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4780, NULL, NULL, 'Wmi-Windows:: The ACL was set on accounts which are members of administrators groups');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4781, NULL, NULL, 'Wmi-Windows:: The name of an account was changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4782, NULL, NULL, 'Wmi-Windows:: The password hash an account was accessed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4783, NULL, NULL, 'Wmi-Windows:: A basic application group was created');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4784, NULL, NULL, 'Wmi-Windows:: A basic application group was changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4785, NULL, NULL, 'Wmi-Windows:: A member was added to a basic application group');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4786, NULL, NULL, 'Wmi-Windows:: A member was removed from a basic application group');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4787, NULL, NULL, 'Wmi-Windows:: A non-member was added to a basic application group');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4788, NULL, NULL, 'Wmi-Windows:: A non-member was removed from a basic application group..');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4789, NULL, NULL, 'Wmi-Windows:: A basic application group was deleted');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4790, NULL, NULL, 'Wmi-Windows:: An LDAP query group was created');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4791, NULL, NULL, 'Wmi-Windows:: A basic application group was changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4792, NULL, NULL, 'Wmi-Windows:: An LDAP query group was deleted');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4793, NULL, NULL, 'Wmi-Windows:: The Password Policy Checking API was called');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4794, NULL, NULL, 'Wmi-Windows:: An attempt was made to set the Directory Services Restore Mode administrator password');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4800, NULL, NULL, 'Wmi-Windows:: The workstation was locked');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4801, NULL, NULL, 'Wmi-Windows:: The workstation was unlocked');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4802, NULL, NULL, 'Wmi-Windows:: The screen saver was invoked');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4803, NULL, NULL, 'Wmi-Windows:: The screen saver was dismissed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4816, NULL, NULL, 'Wmi-Windows:: RPC detected an integrity violation while decrypting an incoming message');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4864, NULL, NULL, 'Wmi-Windows:: A namespace collision was detected');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4865, NULL, NULL, 'Wmi-Windows:: A trusted forest information entry was added');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4866, NULL, NULL, 'Wmi-Windows:: A trusted forest information entry was removed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4867, NULL, NULL, 'Wmi-Windows:: A trusted forest information entry was modified');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4868, NULL, NULL, 'Wmi-Windows:: The certificate manager denied a pending certificate request');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4869, NULL, NULL, 'Wmi-Windows:: Certificate Services received a resubmitted certificate request');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4870, NULL, NULL, 'Wmi-Windows:: Certificate Services revoked a certificate');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4871, NULL, NULL, 'Wmi-Windows:: Certificate Services received a request to publish the certificate revocation list (CRL)');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4872, NULL, NULL, 'Wmi-Windows:: Certificate Services published the certificate revocation list (CRL)');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4873, NULL, NULL, 'Wmi-Windows:: A certificate request extension changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4875, NULL, NULL, 'Wmi-Windows:: Certificate Services received a request to shut down');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4876, NULL, NULL, 'Wmi-Windows:: Certificate Services backup started');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4877, NULL, NULL, 'Wmi-Windows:: Certificate Services backup completed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4878, NULL, NULL, 'Wmi-Windows:: Certificate Services restore started');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4879, NULL, NULL, 'Wmi-Windows:: Certificate Services restore completed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4880, NULL, NULL, 'Wmi-Windows:: Certificate Services started');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4881, NULL, NULL, 'Wmi-Windows:: Certificate Services stopped');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4882, NULL, NULL, 'Wmi-Windows:: The security permissions for Certificate Services changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4883, NULL, NULL, 'Wmi-Windows:: Certificate Services retrieved an archived key');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4884, NULL, NULL, 'Wmi-Windows:: Certificate Services imported a certificate into its database');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4885, NULL, NULL, 'Wmi-Windows:: The audit filter for Certificate Services changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4886, NULL, NULL, 'Wmi-Windows:: Certificate Services received a certificate request');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4887, NULL, NULL, 'Wmi-Windows:: Certificate Services approved a certificate request and issued a certificate');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4888, NULL, NULL, 'Wmi-Windows:: Certificate Services denied a certificate request');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4889, NULL, NULL, 'Wmi-Windows:: Certificate Services set the status of a certificate request to pending');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4890, NULL, NULL, 'Wmi-Windows:: The certificate manager settings for Certificate Services changed.');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4891, NULL, NULL, 'Wmi-Windows:: A configuration entry changed in Certificate Services');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4892, NULL, NULL, 'Wmi-Windows:: A property of Certificate Services changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4893, NULL, NULL, 'Wmi-Windows:: Certificate Services archived a key');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4894, NULL, NULL, 'Wmi-Windows:: Certificate Services imported and archived a key');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4895, NULL, NULL, 'Wmi-Windows:: Certificate Services published the CA certificate to Active Directory Domain Services');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4896, NULL, NULL, 'Wmi-Windows:: One or more rows have been deleted from the certificate database');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4897, NULL, NULL, 'Wmi-Windows:: Role separation enabled');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4898, NULL, NULL, 'Wmi-Windows:: Certificate Services loaded a template');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4899, NULL, NULL, 'Wmi-Windows:: A Certificate Services template was updated');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4900, NULL, NULL, 'Wmi-Windows:: Certificate Services template security was updated');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4902, NULL, NULL, 'Wmi-Windows:: The Per-user audit policy table was created');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4904, NULL, NULL, 'Wmi-Windows:: An attempt was made to register a security event source');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4905, NULL, NULL, 'Wmi-Windows:: An attempt was made to unregister a security event source');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4906, NULL, NULL, 'Wmi-Windows:: The CrashOnAuditFail value has changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4907, NULL, NULL, 'Wmi-Windows:: Auditing settings on object were changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4908, NULL, NULL, 'Wmi-Windows:: Special Groups Logon table modified');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4909, NULL, NULL, 'Wmi-Windows:: The local policy settings for the TBS were changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4910, NULL, NULL, 'Wmi-Windows:: The group policy settings for the TBS were changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4912, NULL, NULL, 'Wmi-Windows:: Per User Audit Policy was changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4928, NULL, NULL, 'Wmi-Windows:: An Active Directory replica source naming context was established');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4929, NULL, NULL, 'Wmi-Windows:: An Active Directory replica source naming context was removed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4930, NULL, NULL, 'Wmi-Windows:: An Active Directory replica source naming context was modified');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4931, NULL, NULL, 'Wmi-Windows:: An Active Directory replica destination naming context was modified');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4932, NULL, NULL, 'Wmi-Windows:: Synchronization of a replica of an Active Directory naming context has begun');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4933, NULL, NULL, 'Wmi-Windows:: Synchronization of a replica of an Active Directory naming context has ended');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4934, NULL, NULL, 'Wmi-Windows:: Attributes of an Active Directory object were replicated');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4935, NULL, NULL, 'Wmi-Windows:: Replication failure begins');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4936, NULL, NULL, 'Wmi-Windows:: Replication failure ends');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4937, NULL, NULL, 'Wmi-Windows:: A lingering object was removed from a replica');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4944, NULL, NULL, 'Wmi-Windows:: The following policy was active when the Windows Firewall started');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4945, NULL, NULL, 'Wmi-Windows:: A rule was listed when the Windows Firewall started');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4946, NULL, NULL, 'Wmi-Windows:: A change has been made to Windows Firewall exception list. A rule was added');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4947, NULL, NULL, 'Wmi-Windows:: A change has been made to Windows Firewall exception list. A rule was modified');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4948, NULL, NULL, 'Wmi-Windows:: A change has been made to Windows Firewall exception list. A rule was deleted');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4949, NULL, NULL, 'Wmi-Windows:: Windows Firewall settings were restored to the default values');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4950, NULL, NULL, 'Wmi-Windows:: A Windows Firewall setting has changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4951, NULL, NULL, 'Wmi-Windows:: A rule has been ignored because its major version number was not recognized by Windows Firewall');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4952, NULL, NULL, 'Wmi-Windows:: Parts of a rule have been ignored because its minor version number was not recognized by Windows Firewall');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4953, NULL, NULL, 'Wmi-Windows:: A rule has been ignored by Windows Firewall because it could not parse the rule');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4954, NULL, NULL, 'Wmi-Windows:: Windows Firewall Group Policy settings has changed. The new settings have been applied');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4956, NULL, NULL, 'Wmi-Windows:: Windows Firewall has changed the active profile');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4957, NULL, NULL, 'Wmi-Windows:: Windows Firewall did not apply the following rule');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4958, NULL, NULL, 'Wmi-Windows:: Windows Firewall did not apply the following rule because the rule referred to items not configured on this computer');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4960, NULL, NULL, 'Wmi-Windows:: IPsec dropped an inbound packet that failed an integrity check');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4961, NULL, NULL, 'Wmi-Windows:: IPsec dropped an inbound packet that failed a replay check');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4962, NULL, NULL, 'Wmi-Windows:: IPsec dropped an inbound packet that failed a replay check');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4963, NULL, NULL, 'Wmi-Windows:: IPsec dropped an inbound clear text packet that should have been secured');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4964, NULL, NULL, 'Wmi-Windows:: Special groups have been assigned to a new logon');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4965, NULL, NULL, 'Wmi-Windows:: IPsec received a packet from a remote computer with an incorrect Security Parameter Index (SPI).');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4976, NULL, NULL, 'Wmi-Windows:: During Main Mode negotiation, IPsec received an invalid negotiation packet.');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4977, NULL, NULL, 'Wmi-Windows:: During Quick Mode negotiation, IPsec received an invalid negotiation packet.');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4978, NULL, NULL, 'Wmi-Windows:: During Extended Mode negotiation, IPsec received an invalid negotiation packet.');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4979, NULL, NULL, 'Wmi-Windows:: IPsec Main Mode and Extended Mode security associations were established.');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4980, NULL, NULL, 'Wmi-Windows:: IPsec Main Mode and Extended Mode security associations were established');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4981, NULL, NULL, 'Wmi-Windows:: IPsec Main Mode and Extended Mode security associations were established');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4982, NULL, NULL, 'Wmi-Windows:: IPsec Main Mode and Extended Mode security associations were established');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4983, NULL, NULL, 'Wmi-Windows:: An IPsec Extended Mode negotiation failed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4984, NULL, NULL, 'Wmi-Windows:: An IPsec Extended Mode negotiation failed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 4985, NULL, NULL, 'Wmi-Windows:: The state of a transaction has changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5024, NULL, NULL, 'Wmi-Windows:: The Windows Firewall Service has started successfully');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5025, NULL, NULL, 'Wmi-Windows:: The Windows Firewall Service has been stopped');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5027, NULL, NULL, 'Wmi-Windows:: The Windows Firewall Service was unable to retrieve the security policy from the local storage');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5028, NULL, NULL, 'Wmi-Windows:: The Windows Firewall Service was unable to parse the new security policy.');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5029, NULL, NULL, 'Wmi-Windows:: The Windows Firewall Service failed to initialize the driver');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5030, NULL, NULL, 'Wmi-Windows:: The Windows Firewall Service failed to start');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5031, NULL, NULL, 'Wmi-Windows:: The Windows Firewall Service blocked an application from accepting incoming connections on the network.');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5032, NULL, NULL, 'Wmi-Windows:: Windows Firewall was unable to notify the user that it blocked an application from accepting incoming connections on the network');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5033, NULL, NULL, 'Wmi-Windows:: The Windows Firewall Driver has started successfully');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5034, NULL, NULL, 'Wmi-Windows:: The Windows Firewall Driver has been stopped');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5035, NULL, NULL, 'Wmi-Windows:: The Windows Firewall Driver failed to start');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5037, NULL, NULL, 'Wmi-Windows:: The Windows Firewall Driver detected critical runtime error. Terminating');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5038, NULL, NULL, 'Wmi-Windows:: Code integrity determined that the image hash of a file is not valid');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5039, NULL, NULL, 'Wmi-Windows:: A registry key was virtualized.');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5040, NULL, NULL, 'Wmi-Windows:: A change has been made to IPsec settings. An Authentication Set was added.');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5041, NULL, NULL, 'Wmi-Windows:: A change has been made to IPsec settings. An Authentication Set was modified');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5042, NULL, NULL, 'Wmi-Windows:: A change has been made to IPsec settings. An Authentication Set was deleted');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5043, NULL, NULL, 'Wmi-Windows:: A change has been made to IPsec settings. A Connection Security Rule was added');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5044, NULL, NULL, 'Wmi-Windows:: A change has been made to IPsec settings. A Connection Security Rule was modified');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5045, NULL, NULL, 'Wmi-Windows:: A change has been made to IPsec settings. A Connection Security Rule was deleted');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5046, NULL, NULL, 'Wmi-Windows:: A change has been made to IPsec settings. A Crypto Set was added');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5047, NULL, NULL, 'Wmi-Windows:: A change has been made to IPsec settings. A Crypto Set was modified');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5048, NULL, NULL, 'Wmi-Windows:: A change has been made to IPsec settings. A Crypto Set was deleted');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5049, NULL, NULL, 'Wmi-Windows:: An IPsec Security Association was deleted');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5050, NULL, NULL, 'Wmi-Windows:: An attempt to programmatically disable the Windows Firewall using a call to INetFwProfile.FirewallEnabled(FALSE');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5051, NULL, NULL, 'Wmi-Windows:: A file was virtualized');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5056, NULL, NULL, 'Wmi-Windows:: A cryptographic self test was performed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5057, NULL, NULL, 'Wmi-Windows:: A cryptographic primitive operation failed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5058, NULL, NULL, 'Wmi-Windows:: Key file operation');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5059, NULL, NULL, 'Wmi-Windows:: Key migration operation');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5060, NULL, NULL, 'Wmi-Windows:: Verification operation failed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5061, NULL, NULL, 'Wmi-Windows:: Cryptographic operation');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5062, NULL, NULL, 'Wmi-Windows:: A kernel-mode cryptographic self test was performed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5063, NULL, NULL, 'Wmi-Windows:: A cryptographic provider operation was attempted');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5064, NULL, NULL, 'Wmi-Windows:: A cryptographic context operation was attempted');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5065, NULL, NULL, 'Wmi-Windows:: A cryptographic context modification was attempted');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5066, NULL, NULL, 'Wmi-Windows:: A cryptographic function operation was attempted');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5067, NULL, NULL, 'Wmi-Windows:: A cryptographic function modification was attempted');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5068, NULL, NULL, 'Wmi-Windows:: A cryptographic function provider operation was attempted');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5069, NULL, NULL, 'Wmi-Windows:: A cryptographic function property operation was attempted');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5070, NULL, NULL, 'Wmi-Windows:: A cryptographic function property operation was attempted');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5120, NULL, NULL, 'Wmi-Windows:: OCSP Responder Service Started');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5121, NULL, NULL, 'Wmi-Windows:: OCSP Responder Service Stopped');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5122, NULL, NULL, 'Wmi-Windows:: A Configuration entry changed in the OCSP Responder Service');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5123, NULL, NULL, 'Wmi-Windows:: A configuration entry changed in the OCSP Responder Service');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5124, NULL, NULL, 'Wmi-Windows:: A security setting was updated on OCSP Responder Service');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5125, NULL, NULL, 'Wmi-Windows:: A request was submitted to OCSP Responder Service');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5126, NULL, NULL, 'Wmi-Windows:: Signing Certificate was automatically updated by the OCSP Responder Service');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5127, NULL, NULL, 'Wmi-Windows:: The OCSP Revocation Provider successfully updated the revocation information');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5136, NULL, NULL, 'Wmi-Windows:: A directory service object was modified');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5137, NULL, NULL, 'Wmi-Windows:: A directory service object was created');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5138, NULL, NULL, 'Wmi-Windows:: A directory service object was undeleted');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5139, NULL, NULL, 'Wmi-Windows:: A directory service object was moved');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5140, NULL, NULL, 'Wmi-Windows:: A network share object was accessed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5141, NULL, NULL, 'Wmi-Windows:: A directory service object was deleted');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5152, NULL, NULL, 'Wmi-Windows:: The Windows Filtering Platform blocked a packet');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5153, NULL, NULL, 'Wmi-Windows:: A more restrictive Windows Filtering Platform filter has blocked a packet');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5154, NULL, NULL, 'Wmi-Windows:: The Windows Filtering Platform has permitted an application or service to listen on a port for incoming connections');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5155, NULL, NULL, 'Wmi-Windows:: The Windows Filtering Platform has blocked an application or service from listening on a port for incoming connections');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5156, NULL, NULL, 'Wmi-Windows:: The Windows Filtering Platform has allowed a connection');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5157, NULL, NULL, 'Wmi-Windows:: The Windows Filtering Platform has blocked a connection');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5158, NULL, NULL, 'Wmi-Windows:: The Windows Filtering Platform has permitted a bind to a local port');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5159, NULL, NULL, 'Wmi-Windows:: The Windows Filtering Platform has blocked a bind to a local port');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5376, NULL, NULL, 'Wmi-Windows:: Credential Manager credentials were backed up');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5377, NULL, NULL, 'Wmi-Windows:: Credential Manager credentials were restored from a backup');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5378, NULL, NULL, 'Wmi-Windows:: The requested credentials delegation was disallowed by policy');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5440, NULL, NULL, 'Wmi-Windows:: The following callout was present when the Windows Filtering Platform Base Filtering Engine started');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5441, NULL, NULL, 'Wmi-Windows:: The following filter was present when the Windows Filtering Platform Base Filtering Engine started');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5442, NULL, NULL, 'Wmi-Windows:: The following provider was present when the Windows Filtering Platform Base Filtering Engine started');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5443, NULL, NULL, 'Wmi-Windows:: The following provider context was present when the Windows Filtering Platform Base Filtering Engine started');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5444, NULL, NULL, 'Wmi-Windows:: The following sub-layer was present when the Windows Filtering Platform Base Filtering Engine started');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5446, NULL, NULL, 'Wmi-Windows:: A Windows Filtering Platform callout has been changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5447, NULL, NULL, 'Wmi-Windows:: A Windows Filtering Platform filter has been changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5448, NULL, NULL, 'Wmi-Windows:: A Windows Filtering Platform provider has been changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5449, NULL, NULL, 'Wmi-Windows:: A Windows Filtering Platform provider context has been changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5450, NULL, NULL, 'Wmi-Windows:: A Windows Filtering Platform sub-layer has been changed');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5451, NULL, NULL, 'Wmi-Windows:: An IPsec Quick Mode security association was established');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5452, NULL, NULL, 'Wmi-Windows:: An IPsec Quick Mode security association ended');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5453, NULL, NULL, 'Wmi-Windows:: An IPsec negotiation with a remote computer failed because the IKE and AuthIP IPsec Keying Modules (IKEEXT) service is not started');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5456, NULL, NULL, 'Wmi-Windows:: PAStore Engine applied Active Directory storage IPsec policy on the computer');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5457, NULL, NULL, 'Wmi-Windows:: PAStore Engine failed to apply Active Directory storage IPsec policy on the computer');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5458, NULL, NULL, 'Wmi-Windows:: PAStore Engine applied locally cached copy of Active Directory storage IPsec policy on the computer');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5459, NULL, NULL, 'Wmi-Windows:: PAStore Engine failed to apply locally cached copy of Active Directory storage IPsec policy on the computer');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5460, NULL, NULL, 'Wmi-Windows:: PAStore Engine applied local registry storage IPsec policy on the computer');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5461, NULL, NULL, 'Wmi-Windows:: PAStore Engine failed to apply local registry storage IPsec policy on the computer');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5462, NULL, NULL, 'Wmi-Windows:: PAStore Engine failed to apply some rules of the active IPsec policy on the computer');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5463, NULL, NULL, 'Wmi-Windows:: PAStore Engine polled for changes to the active IPsec policy and detected no changes');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5464, NULL, NULL, 'Wmi-Windows:: PAStore Engine polled for changes to the active IPsec policy, detected changes, and applied them to IPsec Services');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5465, NULL, NULL, 'Wmi-Windows:: PAStore Engine received a control for forced reloading of IPsec policy and processed the control successfully');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5466, NULL, NULL, 'Wmi-Windows:: PAStore Engine polled for changes to the Active Directory IPsec policy, determined that Active Directory cannot be reached, and will use the cached copy of the Active Directory IPsec policy instead');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5467, NULL, NULL, 'Wmi-Windows:: PAStore Engine polled for changes to the Active Directory IPsec policy, determined that Active Directory can be reached, and found no changes to the policy');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5468, NULL, NULL, 'Wmi-Windows:: PAStore Engine polled for changes to the Active Directory IPsec policy, determined that Active Directory can be reached, found changes to the policy, and applied those changes');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5471, NULL, NULL, 'Wmi-Windows:: PAStore Engine loaded local storage IPsec policy on the computer');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5472, NULL, NULL, 'Wmi-Windows:: PAStore Engine failed to load local storage IPsec policy on the computer');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5473, NULL, NULL, 'Wmi-Windows:: PAStore Engine loaded directory storage IPsec policy on the computer');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5474, NULL, NULL, 'Wmi-Windows:: PAStore Engine failed to load directory storage IPsec policy on the computer');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5477, NULL, NULL, 'Wmi-Windows:: PAStore Engine failed to add quick mode filter');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5478, NULL, NULL, 'Wmi-Windows:: IPsec Services has started successfully');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5479, NULL, NULL, 'Wmi-Windows:: IPsec Services has been shut down successfully');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5480, NULL, NULL, 'Wmi-Windows:: IPsec Services failed to get the complete list of network interfaces on the computer');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5483, NULL, NULL, 'Wmi-Windows:: IPsec Services failed to initialize RPC server. IPsec Services could not be started');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5484, NULL, NULL, 'Wmi-Windows:: IPsec Services has experienced a critical failure and has been shut down');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5485, NULL, NULL, 'Wmi-Windows:: IPsec Services failed to process some IPsec filters on a plug-and-play event for network interfaces');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5632, NULL, NULL, 'Wmi-Windows:: A request was made to authenticate to a wireless network');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5633, NULL, NULL, 'Wmi-Windows:: A request was made to authenticate to a wired network');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5712, NULL, NULL, 'Wmi-Windows:: A Remote Procedure Call (RPC) was attempted');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5888, NULL, NULL, 'Wmi-Windows:: An object in the COM+ Catalog was modified');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5889, NULL, NULL, 'Wmi-Windows:: An object was deleted from the COM+ Catalog');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 5890, NULL, NULL, 'Wmi-Windows:: An object was added to the COM+ Catalog');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 6144, NULL, NULL, 'Wmi-Windows:: Security policy in the group policy objects has been applied successfully');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 6145, NULL, NULL, 'Wmi-Windows:: One or more errors occured while processing security policy in the group policy objects');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 6272, NULL, NULL, 'Wmi-Windows:: Network Policy Server granted access to a user');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 6273, NULL, NULL, 'Wmi-Windows:: Network Policy Server denied access to a user');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 6274, NULL, NULL, 'Wmi-Windows:: Network Policy Server discarded the request for a user');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 6275, NULL, NULL, 'Wmi-Windows:: Network Policy Server discarded the accounting request for a user');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 6276, NULL, NULL, 'Wmi-Windows:: Network Policy Server quarantined a user');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 6277, NULL, NULL, 'Wmi-Windows:: Network Policy Server granted access to a user but put it on probation because the host did not meet the defined health policy');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 6278, NULL, NULL, 'Wmi-Windows:: Network Policy Server granted full access to a user because the host met the defined health policy');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 6279, NULL, NULL, 'Wmi-Windows:: Network Policy Server locked the user account due to repeated failed authentication attempts');
INSERT INTO plugin_sid (plugin_id, sid, category_id, class_id, name) VALUES (1802, 6280, NULL, NULL, 'Wmi-Windows:: Network Policy Server unlocked the user account');
