#!/usr/bin/python -OOt

import sys
sys.path.append('/usr/share/ossim-agent/')
sys.path.append('/usr/local/share/ossim-agent/')

from ossim_agent.Agent import Agent

agent = Agent()
agent.main()


# vim:ts=4 sts=4 tw=79 expandtab:
