#!/usr/bin/php
<?php
/***************************************************************************
*
*   Copyright (c) 2007-2011 AlienVault
*   All rights reserved.
*
****************************************************************************/
$auth=0;

set_time_limit(0);
ob_implicit_flush();
ini_set('include_path', '/usr/share/ossim/include');
ini_set('memory_limit','1024M');
include_once("classes/Session.inc");
$db         = new ossim_db();
$dbconn     = $db->connect();
$allowed_users = Session_activity::get_list($dbconn, " ORDER BY activity desc");
preg_match("/.*PHPSESSID=(\w+).*/", $_ENV["COOKIE"], $matches);
foreach ($allowed_users as $au) {
	# Old check
	#if ( trim($au->get_login()) == trim($_ENV["USER"]) && trim($au->get_id()) == trim($matches[1]) ) {
	#New check with libapache2-mod-auth-alienvault
	if ( trim($au->get_id()) == trim($matches[1]) ) {
	$auth=1;
  }
}
$db->close($dbconn);

if ($auth==1){ exit(0); }
else { exit(1); }

?>
