#!/bin/bash
#
# Init file for the OSSIM agent 
#
# chkconfig: - 93 83
#
# description: Ossim agent
#
# processname: ossim-agent
# config: /etc/ossim/agent/config.cfg

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

if [ -f /etc/sysconfig/ossim-agent ]; then
  . /etc/sysconfig/ossim-agent
fi

# Check networking
[ "${NETWORKING}" == "no" ] && exit 0

# Check python
[ -x "/usr/bin/python" ] || exit 1

# Check ossim-agent file
[ -r "/usr/bin/ossim-agent" ] || exit 1

RETVAL=0
OPTIONS=-d
prog="ossim-agent"

start () {
	echo -n $"Starting $prog: "
	daemon $prog $OPTIONS
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && touch /var/lock/subsys/\$prog
	return $RETVAL
}

stop () {
	echo -n $"Stopping $prog: "
	killproc $prog
	RETVAL=$?
	echo 
	[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/$prog
	return $RETVAL
}

restart () {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  condrestart)
	[ -e /var/lock/subsys/$prog ] && restart
	RETVAL=$?
	;;
  status)
	status $prog
	RETVAL=$?
	;;
  *)
	echo $"Usage: $0 {start|stop|restart|condrestart|status}"
	RETVAL=1
esac

exit $RETVAL
