#!/bin/sh -e

# configuration variables
OSSIM_AGENT_TMP_DIR="/tmp/ossim-agent"

case "$1" in
    upgrade|configure)
        # Hey! ossim-agent's config file must be in its location. If
        # not we shall try to get one to prevent ossim-reconfig to
        # fail.
        if [ ! -f /etc/ossim/agent/config.cfg ]; then
            if [ -f ${OSSIM_AGENT_TMP_DIR}/config.cfg ]; then
                cp ${OSSIM_AGENT_TMP_DIR}/config.cfg /etc/ossim/agent/config.cfg
            else
                touch /etc/ossim/agent/config.cfg
            fi
        fi

        # Execute ossim-reconfig
        if [ -x /usr/bin/ossim-reconfig ]; then
            #if [ -x /usr/bin/postpone ]; then
            #   /usr/bin/postpone --verbose --lock /var/run/ossim-reconfig.lock --output /tmp/ossim-reconfig.XXXXXX --debian /usr/bin/ossim-reconfig -v -c --dpkg
            #else
                /usr/bin/ossim-reconfig -v -c --dpkg
            #fi
        else
            echo "#######################################"
            echo "#######################################"
            echo "Please run ossim-reconfig after install"
            echo "#######################################"
            echo "#######################################"
        fi

        if [ -d ${OSSIM_AGENT_TMP_DIR} ]; then
          rm -r ${OSSIM_AGENT_TMP_DIR}
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac



#DEBHELPER#

exit 0

